@startuml
!theme plain
hide circle
hide empty members

skinparam packageStyle rectangle
skinparam class {
    BackgroundColor White
    ArrowColor #2E86DE
    BorderColor #2c3e50
}

package "DynamoDB Table: LogisticsOperations" {
    
    class "Agregado del Viaje (Partition Key)" as PK << (P, #ff9f43) >> {
        **PK:** TO#103
        ==
        Identificador único de la Orden de Transporte.
        Agrupa toda la información de ejecución.
    }

    class "SK: META" as Meta {
        **SK:** META
        --
        entityType: "TRANSPORT_ORDER"
        status: "ENROUTE"
        driverName: "Gino Baptista"
        assignedWeightKg: 9100.00
        .. Anidados ..
        sales: [ { saleOrderId: 556, invoiceAmount: 1250 } ]
        history: [ { status: "ENROUTE", reason: "Inicio de ruta" } ]
    }

    class "SK: ROUTE#<id>" as Route {
        **SK:** ROUTE#3344
        --
        entityType: "ROUTE"
        encodePolyline: "u{~vB..._a@"
        etaTotalDistanceM: 14500
        .. Anidados (route_delivery_points) ..
        sequence: [ 
          { dispatchDeliveryPointId: 805, order: 1 },
          { dispatchDeliveryPointId: 801, order: 2 }
        ]
    }

    class "SK: INV#PROD#<id>" as Inv {
        **SK:** INV#PROD#30201
        --
        entityType: "INVENTORY_ITEM"
        productName: "Ketchup 900ml"
        expectedQty: 24
        loadedQty: 24
        varianceQty: 0
        status: "MATCH"
    }

    class "SK: DO#<id>" as DO {
        **SK:** DO#90112
        --
        entityType: "DELIVERY_ORDER"
        customerName: "Casa La Ramada"
        status: "DELIVERED"
        .. Anidados (delivery_order_items) ..
        items: [ { productId: 78, deliveredQty: 24 } ]
        .. Anidados (delivery_payment_references) ..
        payments: [ { method: "QR", amount: 200, status: "COMPLETED" } ]
        .. Anidado (proof_of_deliveries) ..
        proofOfDelivery: { receiverName: "Roberto", signatureUrl: "s3://..." }
        .. Anidados (delivery_incidents) ..
        incidents: [ { incidentCode: "CLIENTE_AUSENTE" } ]
        .. Anidados (delivery_order_histories) ..
        history: [ { status: "ARRIVED", changedAt: "08:15:00" } ]
    }

    PK --> Meta : "1 Ítem\n(Cabecera)"
    PK --> Route : "1 Ítem\n(Secuencia geométrica)"
    PK --> Inv : "N Ítems\n(Uno por producto a cargar)"
    PK --> DO : "N Ítems\n(Uno por cliente/parada)"
}

package "DynamoDB Table: TruckTracking" {
    class "Última Posición Flota" as Flota {
        **PK:** FLEET#1 (Distributor ID)
        **SK:** ROUTE#512
        --
        latitude: -17.7834
        longitude: -63.1812
        trackedAt: "2026-07-16T08:24:39Z"
    }
    
    class "Traza Histórica del Viaje" as Traza {
        **PK:** ROUTE#512
        **SK:** TS#2026-07-16T08:24:39Z
        --
        latitude: -17.7834
        longitude: -63.1812
        battery: 74
    }
}
@enduml