// Catálogo de Centros y Distribuidoras desde SAP S/4HANA (Simulación RFC/OData)
//
// Refleja el maestro de centros logísticos (Plant / Storage Location) que residen en SAP ERP
// para sincronizarse hacia la base de datos local `distributors` y delimitarse en `distribution_zones`.

export interface SapDistribuidora {
  sapCode: string
  name: string
  cityId: number
  cityName: string
  address: string
  latitude: number
  longitude: number
  capacityPlts: number
  plantType: 'Centro Principal' | 'Planta Embotelladora' | 'Almacén Cross-Dock' | 'Sucursal de Reparto'
  storageTemp: 'Ambiente / Refrigerado' | 'Seco General' | 'Líquidos y Cervezas'
  sapOrgVentas: string
  sapCanalDistr: string
  syncDate: string
}

export const SAP_DISTRIBUIDORAS_CATALOGO: SapDistribuidora[] = [
  // ═════════════════════════════════════════════════════════════════════════════
  // ── SANTA CRUZ DE LA SIERRA (cityId: 1) ──────────────────────────────────────
  // ═════════════════════════════════════════════════════════════════════════════
  {
    sapCode: 'CD-SCZ-101',
    name: 'DISCRUZ Centro Logístico Santos Dumont',
    cityId: 1,
    cityName: 'Santa Cruz de la Sierra',
    address: 'Av. Santos Dumont entre 7mo y 8vo Anillo',
    latitude: -17.842,
    longitude: -63.181,
    capacityPlts: 2400,
    plantType: 'Almacén Cross-Dock',
    storageTemp: 'Líquidos y Cervezas',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '10 - Directo Mayorista',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-SCZ-102',
    name: 'DISCRUZ Planta Norte Radial 26',
    cityId: 1,
    cityName: 'Santa Cruz de la Sierra',
    address: 'Av. Radial 26 y 5to Anillo N° 450',
    latitude: -17.728,
    longitude: -63.168,
    capacityPlts: 1650,
    plantType: 'Planta Embotelladora',
    storageTemp: 'Ambiente / Refrigerado',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '30 - Horeca Institucional',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-SCZ-103',
    name: 'DISCRUZ Hub Este Mutualista',
    cityId: 1,
    cityName: 'Santa Cruz de la Sierra',
    address: 'Av. Mutualista y 6to Anillo Este',
    latitude: -17.761,
    longitude: -63.132,
    capacityPlts: 1350,
    plantType: 'Sucursal de Reparto',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-SCZ-104',
    name: 'DISCRUZ Planta Parque Industrial Central',
    cityId: 1,
    cityName: 'Santa Cruz de la Sierra',
    address: 'Parque Industrial Mza. 12 Lote 4',
    latitude: -17.748,
    longitude: -63.152,
    capacityPlts: 2800,
    plantType: 'Centro Principal',
    storageTemp: 'Ambiente / Refrigerado',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '10 - Directo Mayorista',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-SCZ-105',
    name: 'DISCRUZ Centro de Distribución Banzer Km 8',
    cityId: 1,
    cityName: 'Santa Cruz de la Sierra',
    address: 'Av. Cristo Redentor (Banzer) Km 8.5',
    latitude: -17.712,
    longitude: -63.178,
    capacityPlts: 3100,
    plantType: 'Centro Principal',
    storageTemp: 'Ambiente / Refrigerado',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '10 - Directo Mayorista',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-SCZ-106',
    name: 'DISCRUZ Depósito Plan 3000 El Mechero',
    cityId: 1,
    cityName: 'Santa Cruz de la Sierra',
    address: 'Av. El Mechero esq. Calle 5, Plan 3000',
    latitude: -17.828,
    longitude: -63.134,
    capacityPlts: 1100,
    plantType: 'Sucursal de Reparto',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-SCZ-107',
    name: 'DISCRUZ Sucursal Villa 1ro de Mayo',
    cityId: 1,
    cityName: 'Santa Cruz de la Sierra',
    address: 'Av. Cumavi y 7mo Anillo Este',
    latitude: -17.788,
    longitude: -63.125,
    capacityPlts: 980,
    plantType: 'Sucursal de Reparto',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-SCZ-108',
    name: 'DISCRUZ Planta Embotelladora El Bajío',
    cityId: 1,
    cityName: 'Santa Cruz de la Sierra',
    address: 'Av. Grigotá y 6to Anillo Suroeste',
    latitude: -17.818,
    longitude: -63.228,
    capacityPlts: 2200,
    plantType: 'Planta Embotelladora',
    storageTemp: 'Líquidos y Cervezas',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '10 - Directo Mayorista',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-SCZ-109',
    name: 'DISCRUZ Hub Mayorista Abasto Central',
    cityId: 1,
    cityName: 'Santa Cruz de la Sierra',
    address: '3er Anillo Interno y Av. Piraí',
    latitude: -17.795,
    longitude: -63.205,
    capacityPlts: 1450,
    plantType: 'Almacén Cross-Dock',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-SCZ-110',
    name: 'DISCRUZ Depósito Tres Pasos al Frente',
    cityId: 1,
    cityName: 'Santa Cruz de la Sierra',
    address: 'Av. Tres Pasos al Frente y 5to Anillo',
    latitude: -17.802,
    longitude: -63.145,
    capacityPlts: 1250,
    plantType: 'Sucursal de Reparto',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },

  // ═════════════════════════════════════════════════════════════════════════════
  // ── MONTERO (cityId: 2) ────────────────────────────────────────────────────
  // ═════════════════════════════════════════════════════════════════════════════
  {
    sapCode: 'CD-MON-201',
    name: 'DISCRUZ Agencia Central Montero',
    cityId: 2,
    cityName: 'Montero',
    address: 'Av. Barrientos esq. Circunvalación Oeste',
    latitude: -17.308,
    longitude: -63.289,
    capacityPlts: 950,
    plantType: 'Centro Principal',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '10 - Directo Mayorista',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-MON-202',
    name: 'DISCRUZ Depósito Satélite Guabirá',
    cityId: 2,
    cityName: 'Montero',
    address: 'Carretera al Ingenio Guabirá Km 2.5',
    latitude: -17.368,
    longitude: -63.208,
    capacityPlts: 720,
    plantType: 'Almacén Cross-Dock',
    storageTemp: 'Líquidos y Cervezas',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-MON-203',
    name: 'DISCRUZ Montero Norte San José',
    cityId: 2,
    cityName: 'Montero',
    address: 'Barrio San José Obrero Av. Tajibos',
    latitude: -17.321,
    longitude: -63.241,
    capacityPlts: 600,
    plantType: 'Sucursal de Reparto',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-MON-204',
    name: 'DISCRUZ Circunvalación Sur Montero',
    cityId: 2,
    cityName: 'Montero',
    address: 'Av. Circunvalación Sur y Calle Bolívar',
    latitude: -17.345,
    longitude: -63.265,
    capacityPlts: 820,
    plantType: 'Sucursal de Reparto',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-MON-205',
    name: 'DISCRUZ Hub Mayorista Villa Busch',
    cityId: 2,
    cityName: 'Montero',
    address: 'Zona Industrial Villa Busch Lote 8',
    latitude: -17.292,
    longitude: -63.255,
    capacityPlts: 1100,
    plantType: 'Almacén Cross-Dock',
    storageTemp: 'Líquidos y Cervezas',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '10 - Directo Mayorista',
    syncDate: '2026-08-26T08:00:00Z',
  },

  // ═════════════════════════════════════════════════════════════════════════════
  // ── WARNES (cityId: 3) ─────────────────────────────────────────────────────
  // ═════════════════════════════════════════════════════════════════════════════
  {
    sapCode: 'CD-WAR-301',
    name: 'DISCRUZ Parque Industrial Latinoamericano',
    cityId: 3,
    cityName: 'Warnes',
    address: 'PILAT Mza. 4, Lote 12, Autovía SCZ-Warnes',
    latitude: -17.486,
    longitude: -63.206,
    capacityPlts: 3200,
    plantType: 'Centro Principal',
    storageTemp: 'Ambiente / Refrigerado',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '10 - Directo Mayorista',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-WAR-302',
    name: 'DISCRUZ Satélite Norte',
    cityId: 3,
    cityName: 'Warnes',
    address: 'Ciudad Satélite Norte Av. Principal N° 120',
    latitude: -17.546,
    longitude: -63.125,
    capacityPlts: 880,
    plantType: 'Sucursal de Reparto',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-WAR-303',
    name: 'DISCRUZ Planta Cervecera Warnes',
    cityId: 3,
    cityName: 'Warnes',
    address: 'Carretera al Norte Km 24',
    latitude: -17.502,
    longitude: -63.175,
    capacityPlts: 2600,
    plantType: 'Planta Embotelladora',
    storageTemp: 'Líquidos y Cervezas',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '10 - Directo Mayorista',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-WAR-304',
    name: 'DISCRUZ Hub Aeropuerto Viru Viru',
    cityId: 3,
    cityName: 'Warnes',
    address: 'Zona Carga Aeropuerto Viru Viru',
    latitude: -17.635,
    longitude: -63.142,
    capacityPlts: 1500,
    plantType: 'Almacén Cross-Dock',
    storageTemp: 'Ambiente / Refrigerado',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '30 - Horeca Institucional',
    syncDate: '2026-08-26T08:00:00Z',
  },

  // ═════════════════════════════════════════════════════════════════════════════
  // ── LA GUARDIA (cityId: 4) ─────────────────────────────────────────────────
  // ═════════════════════════════════════════════════════════════════════════════
  {
    sapCode: 'CD-LGD-401',
    name: 'DISCRUZ La Guardia Central',
    cityId: 4,
    cityName: 'La Guardia',
    address: 'Km 14 Carretera Antigua a Cochabamba',
    latitude: -17.886,
    longitude: -63.272,
    capacityPlts: 1100,
    plantType: 'Centro Principal',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '10 - Directo Mayorista',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-LGD-402',
    name: 'DISCRUZ Km 9 El Carmen',
    cityId: 4,
    cityName: 'La Guardia',
    address: 'Km 9 Av. Simón Bolívar y Los Pinos',
    latitude: -17.946,
    longitude: -63.191,
    capacityPlts: 650,
    plantType: 'Almacén Cross-Dock',
    storageTemp: 'Líquidos y Cervezas',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-LGD-403',
    name: 'DISCRUZ Sucursal San José de La Angostura',
    cityId: 4,
    cityName: 'La Guardia',
    address: 'Carretera a La Angostura Km 22',
    latitude: -18.012,
    longitude: -63.315,
    capacityPlts: 520,
    plantType: 'Sucursal de Reparto',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-LGD-404',
    name: 'DISCRUZ Depósito Km 12 San Miguel',
    cityId: 4,
    cityName: 'La Guardia',
    address: 'Doble Vía Km 12 y Av. San Miguel',
    latitude: -17.865,
    longitude: -63.252,
    capacityPlts: 890,
    plantType: 'Sucursal de Reparto',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },

  // ═════════════════════════════════════════════════════════════════════════════
  // ── COTOCA (cityId: 5) ─────────────────────────────────────────────────────
  // ═════════════════════════════════════════════════════════════════════════════
  {
    sapCode: 'CD-COT-501',
    name: 'DISCRUZ Cotoca Santuario',
    cityId: 5,
    cityName: 'Cotoca',
    address: 'Av. Virgen de Cotoca Km 18',
    latitude: -17.786,
    longitude: -63.072,
    capacityPlts: 900,
    plantType: 'Centro Principal',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '10 - Directo Mayorista',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-COT-502',
    name: 'DISCRUZ Pailas Express',
    cityId: 5,
    cityName: 'Cotoca',
    address: 'Carretera a Puerto Pailas Km 28',
    latitude: -17.846,
    longitude: -62.991,
    capacityPlts: 540,
    plantType: 'Almacén Cross-Dock',
    storageTemp: 'Líquidos y Cervezas',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-COT-503',
    name: 'DISCRUZ Planta Este Campanero',
    cityId: 5,
    cityName: 'Cotoca',
    address: 'Comunidad Campanero Km 21',
    latitude: -17.755,
    longitude: -63.045,
    capacityPlts: 760,
    plantType: 'Planta Embotelladora',
    storageTemp: 'Ambiente / Refrigerado',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '10 - Directo Mayorista',
    syncDate: '2026-08-26T08:00:00Z',
  },
  {
    sapCode: 'CD-COT-504',
    name: 'DISCRUZ Hub Carretera Guarayos',
    cityId: 5,
    cityName: 'Cotoca',
    address: 'Carretera al Norte Chiquitano Km 25',
    latitude: -17.725,
    longitude: -63.015,
    capacityPlts: 620,
    plantType: 'Sucursal de Reparto',
    storageTemp: 'Seco General',
    sapOrgVentas: 'BO01 - Discruz Bolivia',
    sapCanalDistr: '20 - Minorista Tradicional',
    syncDate: '2026-08-26T08:00:00Z',
  },
]

/**
 * Simula una llamada OData / RFC a SAP para obtener los centros de una ciudad.
 * @param cityId Id numérico de la ciudad (1 = Santa Cruz, 2 = Montero, etc.)
 */
export async function consultarDistribuidorasSap(cityId: number): Promise<SapDistribuidora[]> {
  // Simulación de latencia de red SAP (200ms)
  await new Promise((resolve) => setTimeout(resolve, 200))
  return SAP_DISTRIBUIDORAS_CATALOGO.filter((d) => d.cityId === cityId)
}
