// Dataset enriquecido de Historial de Órdenes de Transporte (OTs).
// Estructurado según el esquema real de Base de Datos (db_script.sql):
// transport_orders, routes, trucks, delivery_orders, delivery_order_sales,
// delivery_payment_references, delivery_order_items, proof_of_deliveries, transport_order_assets.

export interface ItemEntregado {
  id: string
  sku: string
  productName: string
  category: string
  orderCode?: string
  orderType?: string
  plannedQty: number
  deliveredQty: number
  returnedQty: number
  unitPrice: number
  total: number
  rejectionReason?: string | null
}

export interface PagoCobranza {
  invoiceId: string
  invoiceAmount: number
  paymentMethod: 'CASH' | 'QR' | 'TRANSFER' | 'CHECK'
  paymentMethodLabel: string
  referenceNumber: string
  amount: number
  currency: string
  status: 'COMPLETED' | 'PENDING'
  notes?: string
}

export interface FotoEvidencia {
  id: string
  title: string
  category: 'FIRMA' | 'CARGA' | 'DOCUMENTO' | 'FACHADA' | 'COMPROBANTE'
  categoryLabel: string
  url?: string
  timestamp: string
  description?: string
  deviceInfo?: string
  coordinates?: string
}

export interface EvidenciaEntrega {
  receiverName: string
  receiverDocument: string
  receiverRelationship: string
  signatureUrl?: string
  signatureHash?: string
  photoUrl?: string
  capturedAt: string
  coordinates?: string
  gpsAccuracy?: string
  photos?: FotoEvidencia[]
}

export interface ParadaHistorial {
  id: string
  sequence: number
  customerName: string
  customerCode: string
  address: string
  zoneName: string
  saleChannel: string
  deliveryNoteNumber: string
  status: 'DELIVERED' | 'PARTIALLY_REJECTED' | 'REJECTED'
  resultCode: 'EXITOSO' | 'RECHAZO_PARCIAL' | 'RECHAZO_TOTAL'
  travelTimeFromPrevious: string
  travelMinutes: number
  arrivedAt: string
  deliveredAt: string
  serviceDuration: string
  items: ItemEntregado[]
  payments: PagoCobranza[]
  proofOfDelivery: EvidenciaEntrega
  incident?: {
    code: string
    description: string
    severity: 'BAJA' | 'MEDIA' | 'ALTA'
  } | null
}

export interface ActivoTransporte {
  assetCode: string
  assetName: string
  dispatchedQty: number
  returnedQty: number
  varianceQty: number
  status: 'RETURNED_OK' | 'DISCREPANCY'
  notes?: string
}

export interface OrdenTransporteHistorial {
  id: string
  code: number
  codeFormatted: string
  distributorName: string
  departureDate: string
  completedDate: string
  dateFormatted: string
  dateIso: string // YYYY-MM-DD para filtrado exacto
  totalKm: number
  assignedWeightKg: number
  assignedVolumeM3: number
  status: 'COMPLETED' | 'CHECKED_OK' | 'DISCREPANCY' | 'ENROUTE'
  statusLabel: string
  truck: {
    id: number
    plate: string
    code: string
    truckType: string
    isRefrigerated: boolean
    capacityKg: number
    capacityM3: number
  }
  driver: {
    name: string
    phone: string
    document: string
  }
  helper: {
    name: string
    phone: string
  }
  supervisor: {
    name: string
  }
  kpis: {
    totalStops: number
    completedStops: number
    successRate: number
    totalInvoiced: number
    totalCollected: number
    collectedCash: number
    collectedQr: number
    collectedTransfer: number
    totalDurationMinutes: number
    driveDurationMinutes: number
    serviceDurationMinutes: number
  }
  logisticAssets: ActivoTransporte[]
  paradas: ParadaHistorial[]
}

export const HISTORIAL_ORDENES_TRANSPORTE: OrdenTransporteHistorial[] = [
  {
    id: 'ot-100451',
    code: 100451,
    codeFormatted: 'OT-100451',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-20T06:30:00',
    completedDate: '2026-08-20T14:45:00',
    dateFormatted: '20/08/2026',
    dateIso: '2026-08-20',
    totalKm: 48.5,
    assignedWeightKg: 3820.0,
    assignedVolumeM3: 15.4,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 12,
      plate: '3012-ABC',
      code: 'CAM-012',
      truckType: 'Furgón 5 Tn',
      isRefrigerated: true,
      capacityKg: 5000,
      capacityM3: 18.0,
    },
    driver: {
      name: 'Carlos Mendoza Vargas',
      phone: '+591 76543210',
      document: '5498214 SC',
    },
    helper: {
      name: 'Roberto Quispe Lima',
      phone: '+591 71239845',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 20,
      completedStops: 18,
      successRate: 90,
      totalInvoiced: 58900.0,
      totalCollected: 55450.0,
      collectedCash: 31200.0,
      collectedQr: 14450.0,
      collectedTransfer: 9800.0,
      totalDurationMinutes: 630,
      driveDurationMinutes: 240,
      serviceDurationMinutes: 390,
    },
    logisticAssets: [
      {
        assetCode: 'PALLET-STD',
        assetName: 'Pallet Madera Estándar (1.20x1.00m)',
        dispatchedQty: 8,
        returnedQty: 8,
        varianceQty: 0,
        status: 'RETURNED_OK',
      },
      {
        assetCode: 'JABA-VERDE',
        assetName: 'Canastilla Plástica Reforzada',
        dispatchedQty: 60,
        returnedQty: 60,
        varianceQty: 0,
        status: 'RETURNED_OK',
      },
      {
        assetCode: 'CART-300KG',
        assetName: 'Carrito de Carga 2 Ruedas',
        dispatchedQty: 1,
        returnedQty: 1,
        varianceQty: 0,
        status: 'RETURNED_OK',
      },
    ],
    paradas: [
      {
        id: 'parada-101',
        sequence: 1,
        customerName: 'Supermercado Fidalga Equipetrol',
        customerCode: 'CLI-8092',
        address: 'Av. San Martín esq. Calle 7 Este',
        zoneName: 'Zona Norte - Equipetrol',
        saleChannel: 'Supermercado',
        deliveryNoteNumber: 'REM-2026-9041',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '18 min (4.2 km)',
        travelMinutes: 18,
        arrivedAt: '07:15',
        deliveredAt: '07:45',
        serviceDuration: '30 min',
        items: [
          {
            id: 'item-1',
            sku: 'CERV-PACE-620',
            productName: 'Cerveza Paceña Pilsener 620ml x12',
            category: 'Cervezas',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 15,
            deliveredQty: 15,
            returnedQty: 0,
            unitPrice: 120.0,
            total: 1800.0,
          },
          {
            id: 'item-1b',
            sku: 'CERV-HUAR-710',
            productName: 'Cerveza Huari Tradicional 710ml x12',
            category: 'Cervezas',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 8,
            deliveredQty: 8,
            returnedQty: 0,
            unitPrice: 155.0,
            total: 1240.0,
          },
          {
            id: 'item-1c',
            sku: 'CERV-STELLA-330',
            productName: 'Stella Artois 330ml Pack x24',
            category: 'Premium',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 4,
            deliveredQty: 4,
            returnedQty: 0,
            unitPrice: 175.0,
            total: 700.0,
          },
          {
            id: 'item-1d',
            sku: 'CERV-CORONA-355',
            productName: 'Corona Extra 355ml x24',
            category: 'Premium',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 3,
            deliveredQty: 3,
            returnedQty: 0,
            unitPrice: 165.0,
            total: 495.0,
          },
          {
            id: 'item-1e',
            sku: 'SODA-PEPSI-3L',
            productName: 'Gaseosa Pepsi 3L x4',
            category: 'Gaseosas',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 5,
            deliveredQty: 5,
            returnedQty: 0,
            unitPrice: 52.0,
            total: 260.0,
          },
          {
            id: 'item-1f',
            sku: 'SODA-7UP-2L',
            productName: 'Gaseosa 7Up 2L x6',
            category: 'Gaseosas',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 4,
            deliveredQty: 4,
            returnedQty: 0,
            unitPrice: 42.0,
            total: 168.0,
          },
          {
            id: 'item-1g',
            sku: 'AGUA-VITA-2L',
            productName: 'Agua Mineral Vital 2L Sin Gas x6',
            category: 'Aguas',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 3,
            deliveredQty: 3,
            returnedQty: 0,
            unitPrice: 38.0,
            total: 114.0,
          },
          {
            id: 'item-1h',
            sku: 'JUGO-DELI-1L',
            productName: 'Jugo Del Valle Durazno 1L x12',
            category: 'Jugos',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 65.0,
            total: 130.0,
          },
          {
            id: 'item-1i',
            sku: 'CERV-PACE-LATA-354',
            productName: 'Cerveza Paceña en Lata 354ml x24',
            category: 'Cervezas',
            orderCode: 'PED-2026-8804',
            orderType: 'Recarga Urgente',
            plannedQty: 6,
            deliveredQty: 6,
            returnedQty: 0,
            unitPrice: 140.0,
            total: 840.0,
          },
          {
            id: 'item-1j',
            sku: 'CERV-HUAR-MIEL-330',
            productName: 'Huari con Miel 330ml Pack x24',
            category: 'Premium',
            orderCode: 'PED-2026-8804',
            orderType: 'Recarga Urgente',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 180.0,
            total: 360.0,
          },
          {
            id: 'item-1k',
            sku: 'ENERG-MONSTER-473',
            productName: 'Monster Energy Drink 473ml x12',
            category: 'Energizantes',
            orderCode: 'PED-2026-8804',
            orderType: 'Recarga Urgente',
            plannedQty: 3,
            deliveredQty: 3,
            returnedQty: 0,
            unitPrice: 184.0,
            total: 552.0,
          },
          {
            id: 'item-1l',
            sku: 'ENERG-RED-BULL-250',
            productName: 'Red Bull Energy Drink 250ml x24',
            category: 'Energizantes',
            orderCode: 'PED-2026-8804',
            orderType: 'Recarga Urgente',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 240.0,
            total: 480.0,
          },
          {
            id: 'item-1m',
            sku: 'SODA-GUAR-2L',
            productName: 'Gaseosa Guaraná Antarctica 2L x6',
            category: 'Gaseosas',
            orderCode: 'PED-2026-8804',
            orderType: 'Recarga Urgente',
            plannedQty: 4,
            deliveredQty: 4,
            returnedQty: 0,
            unitPrice: 48.0,
            total: 192.0,
          },
          {
            id: 'item-1n',
            sku: 'SODA-MIRINDA-2L',
            productName: 'Gaseosa Mirinda Naranja 2L x6',
            category: 'Gaseosas',
            orderCode: 'PED-2026-8804',
            orderType: 'Recarga Urgente',
            plannedQty: 3,
            deliveredQty: 3,
            returnedQty: 0,
            unitPrice: 40.0,
            total: 120.0,
          },
          {
            id: 'item-1o',
            sku: 'AGUA-VITA-CONGAS-2L',
            productName: 'Agua Vital con Gas 2L x6',
            category: 'Aguas',
            orderCode: 'PED-2026-8809',
            orderType: 'Promoción Especial',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 40.0,
            total: 80.0,
          },
          {
            id: 'item-1p',
            sku: 'AGUA-VITA-500ML',
            productName: 'Agua Vital 500ml Pack x12',
            category: 'Aguas',
            orderCode: 'PED-2026-8809',
            orderType: 'Promoción Especial',
            plannedQty: 4,
            deliveredQty: 4,
            returnedQty: 0,
            unitPrice: 30.0,
            total: 120.0,
          },
          {
            id: 'item-1q',
            sku: 'MALTA-REAL-330',
            productName: 'Malta Real Nutritiva 330ml x24',
            category: 'Maltas',
            orderCode: 'PED-2026-8809',
            orderType: 'Promoción Especial',
            plannedQty: 3,
            deliveredQty: 3,
            returnedQty: 0,
            unitPrice: 95.0,
            total: 285.0,
          },
          {
            id: 'item-1r',
            sku: 'JUGO-DELI-MANZ-1L',
            productName: 'Jugo Del Valle Manzana 1L x12',
            category: 'Jugos',
            orderCode: 'PED-2026-8809',
            orderType: 'Promoción Especial',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 65.0,
            total: 130.0,
          },
          {
            id: 'item-1s',
            sku: 'JUGO-DELI-NAR-1L',
            productName: 'Jugo Del Valle Naranja 1L x12',
            category: 'Jugos',
            orderCode: 'PED-2026-8809',
            orderType: 'Promoción Especial',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 65.0,
            total: 130.0,
          },
          {
            id: 'item-1t',
            sku: 'CERV-BUD-355',
            productName: 'Cerveza Budweiser 355ml x24',
            category: 'Premium',
            orderCode: 'PED-2026-8809',
            orderType: 'Promoción Especial',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 160.0,
            total: 320.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104928',
            invoiceAmount: 4800.0,
            paymentMethod: 'TRANSFER',
            paymentMethodLabel: 'Transferencia BNB',
            referenceNumber: 'TRF-BNB-994821',
            amount: 4800.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Lic. Mariana Justiniano',
          receiverDocument: 'CI 4598122 SC',
          receiverRelationship: 'Encargada de Recepción y Almacén',
          capturedAt: '2026-08-21 07:44:12',
          coordinates: '-17.77892, -63.19012 (Av. San Martín esq. Calle 7)',
          gpsAccuracy: '± 3.8 metros (GPS Verificado)',
          signatureHash: 'SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
          signatureUrl: 'data:image/svg+xml;utf8,<svg ... />',
          photos: [
            {
              id: 'evid-1',
              title: 'Firma Digital de Recepción',
              category: 'FIRMA',
              categoryLabel: 'Firma del Receptor',
              timestamp: '07:44:12',
              coordinates: '-17.77892, -63.19012',
              deviceInfo: 'Handheld Zebra TC26 · Android 12',
              description: 'Firma digital de recepción capturada en pantalla táctil con validación de hora y geolocalización en punto.',
            },
            {
              id: 'evid-2',
              title: 'Fotografía de la Entrega',
              category: 'CARGA',
              categoryLabel: 'Fotografía de Entrega',
              timestamp: '07:42:05',
              coordinates: '-17.77891, -63.19015',
              deviceInfo: 'Cámara trasera 13MP Zebra TC26',
              description: 'Fotografía de la mercadería entregada y descargada en el almacén del cliente en perfecto estado.',
            },
          ],
        },
      },
      {
        id: 'parada-102',
        sequence: 2,
        customerName: 'Abarrotes & Licorería Don Carlos',
        customerCode: 'CLI-5531',
        address: 'Av. Busch esq. 3er Anillo Interno',
        zoneName: 'Zona Oeste - Busch',
        saleChannel: 'Tradicional',
        deliveryNoteNumber: 'REM-2026-9042',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '14 min (3.1 km)',
        travelMinutes: 14,
        arrivedAt: '08:00',
        deliveredAt: '08:25',
        serviceDuration: '25 min',
        items: [
          {
            id: 'item-2',
            sku: 'CERV-HUAR-710',
            productName: 'Cerveza Huari Tradicional 710ml x12',
            category: 'Cervezas',
            plannedQty: 20,
            deliveredQty: 20,
            returnedQty: 0,
            unitPrice: 155.0,
            total: 3100.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104929',
            invoiceAmount: 3100.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BMSC-883109',
            amount: 3100.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Carlos Gutiérrez Aguilera',
          receiverDocument: 'CI 3829104 SC',
          receiverRelationship: 'Propietario',
          capturedAt: '08:22',
        },
      },
      {
        id: 'parada-103',
        sequence: 3,
        customerName: 'Micromercado El Triunfo',
        customerCode: 'CLI-4120',
        address: 'Calle Libertad #420 (Casco Viejo)',
        zoneName: 'Zona Centro',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9043',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '12 min (2.8 km)',
        travelMinutes: 12,
        arrivedAt: '08:38',
        deliveredAt: '09:00',
        serviceDuration: '22 min',
        items: [
          {
            id: 'item-3',
            sku: 'CERV-PACE-LATA',
            productName: 'Paceña en Lata 354ml Pack x24',
            category: 'Cervezas',
            plannedQty: 15,
            deliveredQty: 15,
            returnedQty: 0,
            unitPrice: 140.0,
            total: 2100.0,
          },
          {
            id: 'item-3b',
            sku: 'AGUA-VITA-2L',
            productName: 'Agua Mineral Vital 2L Sin Gas x6',
            category: 'Aguas',
            plannedQty: 8,
            deliveredQty: 8,
            returnedQty: 0,
            unitPrice: 38.0,
            total: 304.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104930',
            invoiceAmount: 2404.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008912',
            amount: 2404.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Teresa Ramos',
          receiverDocument: 'CI 2948102 SC',
          receiverRelationship: 'Administradora',
          capturedAt: '08:58',
        },
      },
      {
        id: 'parada-104',
        sequence: 4,
        customerName: 'Comercializadora San Roque',
        customerCode: 'CLI-9921',
        address: 'Av. Grigotá esq. 2do Anillo',
        zoneName: 'Zona Sur - La Ramada',
        saleChannel: 'Mayorista',
        deliveryNoteNumber: 'REM-2026-9044',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '16 min (3.5 km)',
        travelMinutes: 16,
        arrivedAt: '09:18',
        deliveredAt: '09:48',
        serviceDuration: '30 min',
        items: [
          {
            id: 'item-4',
            sku: 'CERV-PACE-620',
            productName: 'Cerveza Paceña Pilsener 620ml x12',
            category: 'Cervezas',
            plannedQty: 50,
            deliveredQty: 50,
            returnedQty: 0,
            unitPrice: 118.0,
            total: 5900.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104931',
            invoiceAmount: 5900.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008913',
            amount: 5900.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Gonzalo Peñaranda',
          receiverDocument: 'CI 4892011 SC',
          receiverRelationship: 'Jefe de Almacén',
          capturedAt: '09:45',
        },
      },
      {
        id: 'parada-105',
        sequence: 5,
        customerName: 'Hipermaxi Los Pozos',
        customerCode: 'CLI-8095',
        address: 'Av. Aroma esq. 6 de Agosto',
        zoneName: 'Zona Este - Los Pozos',
        saleChannel: 'Supermercado',
        deliveryNoteNumber: 'REM-2026-9045',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '15 min (3.0 km)',
        travelMinutes: 15,
        arrivedAt: '10:05',
        deliveredAt: '10:35',
        serviceDuration: '30 min',
        items: [
          {
            id: 'item-5',
            sku: 'CERV-STELLA-330',
            productName: 'Stella Artois 330ml Pack x24',
            category: 'Premium',
            plannedQty: 18,
            deliveredQty: 18,
            returnedQty: 0,
            unitPrice: 175.0,
            total: 3150.0,
          },
          {
            id: 'item-5b',
            sku: 'CERV-CORONA-355',
            productName: 'Corona Extra 355ml x24',
            category: 'Premium',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 164.5,
            total: 1645.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104932',
            invoiceAmount: 4795.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BCP-772910',
            amount: 4795.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Víctor Hugo Claros',
          receiverDocument: 'CI 6029311 SC',
          receiverRelationship: 'Supervisor de Plataforma',
          capturedAt: '10:32',
        },
      },
      {
        id: 'parada-106',
        sequence: 6,
        customerName: 'Pulpería La Tradición',
        customerCode: 'CLI-3180',
        address: 'Av. Virgen de Cotoca esq. 4to Anillo',
        zoneName: 'Zona Pampa de la Isla',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9046',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '12 min (2.5 km)',
        travelMinutes: 12,
        arrivedAt: '10:50',
        deliveredAt: '11:10',
        serviceDuration: '20 min',
        items: [
          {
            id: 'item-6',
            sku: 'SODA-7UP-2L',
            productName: 'Gaseosa 7Up 2L x6',
            category: 'Gaseosas',
            plannedQty: 8,
            deliveredQty: 8,
            returnedQty: 0,
            unitPrice: 42.0,
            total: 336.0,
          },
          {
            id: 'item-6b',
            sku: 'ENERG-MONSTER-473',
            productName: 'Monster Energy 473ml x12',
            category: 'Energizantes',
            plannedQty: 1,
            deliveredQty: 1,
            returnedQty: 0,
            unitPrice: 184.0,
            total: 184.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104933',
            invoiceAmount: 520.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008914',
            amount: 520.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Rosario Salvatierra',
          receiverDocument: 'CI 3901923 SC',
          receiverRelationship: 'Propietaria',
          capturedAt: '11:08',
        },
      },
      {
        id: 'parada-107',
        sequence: 7,
        customerName: 'Tienda Doña Carmen',
        customerCode: 'CLI-2201',
        address: 'Calle 10 de Agosto #84',
        zoneName: 'Zona Pampa de la Isla',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9047',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '8 min (1.4 km)',
        travelMinutes: 8,
        arrivedAt: '11:20',
        deliveredAt: '11:35',
        serviceDuration: '15 min',
        items: [
          {
            id: 'item-7',
            sku: 'JUGO-DELI-1L',
            productName: 'Jugo Del Valle Durazno 1L x12',
            category: 'Jugos',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 65.0,
            total: 650.0,
          },
          {
            id: 'item-7b',
            sku: 'SODA-PEPSI-3L',
            productName: 'Gaseosa Pepsi 3L x4',
            category: 'Gaseosas',
            plannedQty: 11,
            deliveredQty: 11,
            returnedQty: 0,
            unitPrice: 52.0,
            total: 572.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104934',
            invoiceAmount: 1222.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BNB-338210',
            amount: 1222.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Carmen Ortiz',
          receiverDocument: 'CI 5019283 SC',
          receiverRelationship: 'Dueña',
          capturedAt: '11:33',
        },
      },
      {
        id: 'parada-108',
        sequence: 8,
        customerName: 'Licorería El Trébol',
        customerCode: 'CLI-5502',
        address: 'Av. Cumavi esq. 3er Anillo',
        zoneName: 'Zona Villa 1ro de Mayo',
        saleChannel: 'Tradicional',
        deliveryNoteNumber: 'REM-2026-9048',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '12 min (2.9 km)',
        travelMinutes: 12,
        arrivedAt: '11:48',
        deliveredAt: '12:08',
        serviceDuration: '20 min',
        items: [
          {
            id: 'item-8',
            sku: 'CERV-HUAR-710',
            productName: 'Cerveza Huari Tradicional 710ml x12',
            category: 'Cervezas',
            plannedQty: 20,
            deliveredQty: 20,
            returnedQty: 0,
            unitPrice: 155.0,
            total: 3100.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104935',
            invoiceAmount: 3100.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008915',
            amount: 3100.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Marcos Terrazas',
          receiverDocument: 'CI 4109283 SC',
          receiverRelationship: 'Administrador',
          capturedAt: '12:05',
        },
      },
      {
        id: 'parada-109',
        sequence: 9,
        customerName: 'Minimarket 24/7 Radial 10',
        customerCode: 'CLI-4410',
        address: 'Av. Radial 10 esq. 4to Anillo',
        zoneName: 'Zona Sur - Radial 10',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9049',
        status: 'PARTIALLY_REJECTED',
        resultCode: 'RECHAZO_PARCIAL',
        travelTimeFromPrevious: '11 min (2.3 km)',
        travelMinutes: 11,
        arrivedAt: '12:20',
        deliveredAt: '12:45',
        serviceDuration: '25 min',
        items: [
          {
            id: 'item-9a',
            sku: 'CERV-PACE-620',
            productName: 'Cerveza Paceña Pilsener 620ml x12',
            category: 'Cervezas',
            plannedQty: 10,
            deliveredQty: 8,
            returnedQty: 2,
            unitPrice: 120.0,
            total: 960.0,
            rejectionReason: '2 cajas con botellas rotas por golpe en transporte',
          },
          {
            id: 'item-9b',
            sku: 'CERV-PACE-LATA',
            productName: 'Paceña en Lata 354ml Pack x24',
            category: 'Cervezas',
            plannedQty: 5,
            deliveredQty: 5,
            returnedQty: 0,
            unitPrice: 140.0,
            total: 700.0,
          },
          {
            id: 'item-9c',
            sku: 'ENERG-MONSTER-473',
            productName: 'Monster Energy 473ml x12',
            category: 'Energizantes',
            plannedQty: 1,
            deliveredQty: 1,
            returnedQty: 0,
            unitPrice: 184.0,
            total: 184.0,
          },
          {
            id: 'item-9d',
            sku: 'SODA-PEPSI-3L',
            productName: 'Gaseosa Pepsi 3L x4',
            category: 'Gaseosas',
            plannedQty: 3,
            deliveredQty: 3,
            returnedQty: 0,
            unitPrice: 52.0,
            total: 156.0,
          },
          {
            id: 'item-9e',
            sku: 'AGUA-VITA-2L',
            productName: 'Agua Mineral Vital 2L Sin Gas x6',
            category: 'Aguas',
            plannedQty: 4,
            deliveredQty: 4,
            returnedQty: 0,
            unitPrice: 38.0,
            total: 152.0,
          },
          {
            id: 'item-9f',
            sku: 'JUGO-DELI-1L',
            productName: 'Jugo Del Valle Durazno 1L x12',
            category: 'Jugos',
            plannedQty: 1,
            deliveredQty: 1,
            returnedQty: 0,
            unitPrice: 65.0,
            total: 65.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104936',
            invoiceAmount: 2160.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BMSC-441092',
            amount: 2160.0,
            currency: 'BOB',
            status: 'COMPLETED',
            notes: 'Descuento aplicado por 2 cajas dañadas',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Sandro Aguilera',
          receiverDocument: 'CI 4892019 SC',
          receiverRelationship: 'Encargado de Local',
          capturedAt: '12:42',
        },
        incident: {
          code: 'ROTURA_TRANSITO',
          description: 'Rechazo parcial de 2 cajas por rotura. Supervisor notificado.',
          severity: 'MEDIA',
        },
      },
      {
        id: 'parada-110',
        sequence: 10,
        customerName: 'Abarrotes Santa Rosa',
        customerCode: 'CLI-3304',
        address: 'Calle Lemoine #52',
        zoneName: 'Zona Sur - Santos Dumont',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9050',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '10 min (2.1 km)',
        travelMinutes: 10,
        arrivedAt: '12:56',
        deliveredAt: '13:16',
        serviceDuration: '20 min',
        items: [
          {
            id: 'item-10',
            sku: 'MALT-REAL-330',
            productName: 'Malta Real Mini 330ml x24',
            category: 'Maltas',
            plannedQty: 15,
            deliveredQty: 15,
            returnedQty: 0,
            unitPrice: 95.0,
            total: 1425.0,
          },
          {
            id: 'item-10b',
            sku: 'AGUA-VITA-2L',
            productName: 'Agua Mineral Vital 2L Sin Gas x6',
            category: 'Aguas',
            plannedQty: 15,
            deliveredQty: 15,
            returnedQty: 0,
            unitPrice: 38.0,
            total: 570.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104937',
            invoiceAmount: 1995.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008916',
            amount: 1995.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Rosa Claros de Vaca',
          receiverDocument: 'CI 2819203 SC',
          receiverRelationship: 'Dueña',
          capturedAt: '13:14',
        },
      },
      {
        id: 'parada-111',
        sequence: 11,
        customerName: 'Supermercado IC Norte Sur',
        customerCode: 'CLI-8104',
        address: 'Av. Santos Dumont esq. 5to Anillo',
        zoneName: 'Zona Sur - Santos Dumont',
        saleChannel: 'Supermercado',
        deliveryNoteNumber: 'REM-2026-9051',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '9 min (1.8 km)',
        travelMinutes: 9,
        arrivedAt: '13:26',
        deliveredAt: '13:56',
        serviceDuration: '30 min',
        items: [
          {
            id: 'item-11',
            sku: 'CERV-PACE-620',
            productName: 'Cerveza Paceña Pilsener 620ml x12',
            category: 'Cervezas',
            plannedQty: 40,
            deliveredQty: 40,
            returnedQty: 0,
            unitPrice: 120.0,
            total: 4800.0,
          },
          {
            id: 'item-11b',
            sku: 'CERV-CORONA-355',
            productName: 'Corona Extra 355ml x24',
            category: 'Premium',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 165.0,
            total: 1650.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104938',
            invoiceAmount: 6450.0,
            paymentMethod: 'TRANSFER',
            paymentMethodLabel: 'Transferencia BNB',
            referenceNumber: 'TRF-BNB-883901',
            amount: 6450.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Ing. Fabio Mendoza',
          receiverDocument: 'CI 4901928 SC',
          receiverRelationship: 'Jefe de Plataforma',
          capturedAt: '13:52',
        },
      },
      {
        id: 'parada-112',
        sequence: 12,
        customerName: 'Comercial El Pahuichi',
        customerCode: 'CLI-6019',
        address: 'Av. Radial 13 esq. Calle 5',
        zoneName: 'Zona Sur - Radial 13',
        saleChannel: 'Tradicional',
        deliveryNoteNumber: 'REM-2026-9052',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '10 min (2.2 km)',
        travelMinutes: 10,
        arrivedAt: '14:07',
        deliveredAt: '14:27',
        serviceDuration: '20 min',
        items: [
          {
            id: 'item-12',
            sku: 'SODA-PEPSI-3L',
            productName: 'Gaseosa Pepsi 3L x4',
            category: 'Gaseosas',
            plannedQty: 30,
            deliveredQty: 30,
            returnedQty: 0,
            unitPrice: 52.0,
            total: 1560.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104939',
            invoiceAmount: 1560.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008917',
            amount: 1560.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Guillermo Paz',
          receiverDocument: 'CI 3901823 SC',
          receiverRelationship: 'Propietario',
          capturedAt: '14:25',
        },
      },
      {
        id: 'parada-113',
        sequence: 13,
        customerName: 'Bodega San José',
        customerCode: 'CLI-2980',
        address: 'Calle 3 esq. Av. Moscú',
        zoneName: 'Zona Moscú',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9053',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '8 min (1.7 km)',
        travelMinutes: 8,
        arrivedAt: '14:36',
        deliveredAt: '14:51',
        serviceDuration: '15 min',
        items: [
          {
            id: 'item-13',
            sku: 'CERV-PACE-LATA',
            productName: 'Paceña en Lata 354ml Pack x24',
            category: 'Cervezas',
            plannedQty: 7,
            deliveredQty: 7,
            returnedQty: 0,
            unitPrice: 140.0,
            total: 980.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104940',
            invoiceAmount: 980.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BNB-119203',
            amount: 980.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'José Luis Flores',
          receiverDocument: 'CI 4810293 SC',
          receiverRelationship: 'Dueño',
          capturedAt: '14:49',
        },
      },
      {
        id: 'parada-114',
        sequence: 14,
        customerName: 'Licorería La Previa',
        customerCode: 'CLI-5520',
        address: 'Doble Vía La Guardia Km 5',
        zoneName: 'Zona Doble Vía',
        saleChannel: 'Tradicional',
        deliveryNoteNumber: 'REM-2026-9054',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '12 min (2.9 km)',
        travelMinutes: 12,
        arrivedAt: '15:04',
        deliveredAt: '15:24',
        serviceDuration: '20 min',
        items: [
          {
            id: 'item-14',
            sku: 'CERV-STELLA-330',
            productName: 'Stella Artois 330ml Pack x24',
            category: 'Premium',
            plannedQty: 15,
            deliveredQty: 15,
            returnedQty: 0,
            unitPrice: 175.0,
            total: 2625.0,
          },
          {
            id: 'item-14b',
            sku: 'CERV-PACE-620',
            productName: 'Cerveza Paceña Pilsener 620ml x12',
            category: 'Cervezas',
            plannedQty: 12,
            deliveredQty: 12,
            returnedQty: 0,
            unitPrice: 120.0,
            total: 1440.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104941',
            invoiceAmount: 4065.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008918',
            amount: 4065.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Mauricio Siles',
          receiverDocument: 'CI 5901823 SC',
          receiverRelationship: 'Encargado',
          capturedAt: '15:21',
        },
      },
      {
        id: 'parada-115',
        sequence: 15,
        customerName: 'Micromercado Belén',
        customerCode: 'CLI-4302',
        address: 'Av. Marcelo Quiroga Santa Cruz',
        zoneName: 'Zona Oeste - Pirai',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9055',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '11 min (2.4 km)',
        travelMinutes: 11,
        arrivedAt: '15:36',
        deliveredAt: '15:51',
        serviceDuration: '15 min',
        items: [
          {
            id: 'item-15',
            sku: 'JUGO-DELI-1L',
            productName: 'Jugo Del Valle Manzana 1L x12',
            category: 'Jugos',
            plannedQty: 12,
            deliveredQty: 12,
            returnedQty: 0,
            unitPrice: 65.0,
            total: 780.0,
          },
          {
            id: 'item-15b',
            sku: 'AGUA-VITA-2L',
            productName: 'Agua Mineral Vital 2L Sin Gas x6',
            category: 'Aguas',
            plannedQty: 16,
            deliveredQty: 16,
            returnedQty: 0,
            unitPrice: 38.0,
            total: 608.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104942',
            invoiceAmount: 1388.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BCP-991024',
            amount: 1388.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Belén Justiniano',
          receiverDocument: 'CI 4019283 SC',
          receiverRelationship: 'Propietaria',
          capturedAt: '15:49',
        },
      },
      {
        id: 'parada-116',
        sequence: 16,
        customerName: 'Depósito Mayorista El Oriente',
        customerCode: 'CLI-9102',
        address: '4to Anillo esq. Av. Roca y Coronado',
        zoneName: 'Zona Oeste - Roca y Coronado',
        saleChannel: 'Mayorista',
        deliveryNoteNumber: 'REM-2026-9056',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '14 min (3.6 km)',
        travelMinutes: 14,
        arrivedAt: '16:06',
        deliveredAt: '16:36',
        serviceDuration: '30 min',
        items: [
          {
            id: 'item-16',
            sku: 'CERV-PACE-620',
            productName: 'Cerveza Paceña Pilsener 620ml x12',
            category: 'Cervezas',
            plannedQty: 70,
            deliveredQty: 70,
            returnedQty: 0,
            unitPrice: 118.0,
            total: 8260.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104943',
            invoiceAmount: 8260.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008919',
            amount: 8260.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Don Waldo Rivero',
          receiverDocument: 'CI 3109283 SC',
          receiverRelationship: 'Gerente Comercial',
          capturedAt: '16:33',
        },
      },
      {
        id: 'parada-117',
        sequence: 17,
        customerName: 'Pulpería El Carmen',
        customerCode: 'CLI-2104',
        address: 'Calle Barach #33 (Barrio Sirari)',
        zoneName: 'Zona Sirari',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9057',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '10 min (2.0 km)',
        travelMinutes: 10,
        arrivedAt: '16:47',
        deliveredAt: '17:02',
        serviceDuration: '15 min',
        items: [
          {
            id: 'item-17',
            sku: 'CERV-HUAR-710',
            productName: 'Cerveza Huari Tradicional 710ml x12',
            category: 'Cervezas',
            plannedQty: 4,
            deliveredQty: 4,
            returnedQty: 0,
            unitPrice: 155.0,
            total: 620.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104944',
            invoiceAmount: 620.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008920',
            amount: 620.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Carmen Vaca Díez',
          receiverDocument: 'CI 2901823 SC',
          receiverRelationship: 'Dueña',
          capturedAt: '17:00',
        },
      },
      {
        id: 'parada-118',
        sequence: 18,
        customerName: 'Tienda Don Mario',
        customerCode: 'CLI-3310',
        address: 'Calle Los Cusis #120',
        zoneName: 'Zona Norte - Beni',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9058',
        status: 'REJECTED',
        resultCode: 'RECHAZO_TOTAL',
        travelTimeFromPrevious: '12 min (2.5 km)',
        travelMinutes: 12,
        arrivedAt: '17:15',
        deliveredAt: '17:30',
        serviceDuration: '15 min',
        items: [
          {
            id: 'item-18',
            sku: 'CERV-PACE-620',
            productName: 'Cerveza Paceña Pilsener 620ml x12',
            category: 'Cervezas',
            plannedQty: 10,
            deliveredQty: 0,
            returnedQty: 10,
            unitPrice: 120.0,
            total: 0.0,
            rejectionReason: 'Local cerrado. Sin personal receptor en horario pactado',
          },
        ],
        payments: [],
        proofOfDelivery: {
          receiverName: 'Sin receptor (Cerrado)',
          receiverDocument: 'N/A',
          receiverRelationship: 'Local cerrado',
          capturedAt: '17:28',
        },
        incident: {
          code: 'CLIENTE_CERRADO',
          description: 'Local cerrado. Chofer esperó 15 min y realizó 2 llamadas sin respuesta.',
          severity: 'ALTA',
        },
      },
      {
        id: 'parada-119',
        sequence: 19,
        customerName: 'Minimarket Las Palmeras',
        customerCode: 'CLI-4490',
        address: 'Av. Beni esq. 3er Anillo Externo',
        zoneName: 'Zona Norte - Beni',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9059',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '9 min (1.8 km)',
        travelMinutes: 9,
        arrivedAt: '17:40',
        deliveredAt: '18:00',
        serviceDuration: '20 min',
        items: [
          {
            id: 'item-19',
            sku: 'CERV-CORONA-355',
            productName: 'Corona Extra 355ml x24',
            category: 'Premium',
            plannedQty: 8,
            deliveredQty: 8,
            returnedQty: 0,
            unitPrice: 165.0,
            total: 1320.0,
          },
          {
            id: 'item-19b',
            sku: 'ENERG-MONSTER-473',
            productName: 'Monster Energy 473ml x12',
            category: 'Energizantes',
            plannedQty: 5,
            deliveredQty: 5,
            returnedQty: 0,
            unitPrice: 184.0,
            total: 920.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104945',
            invoiceAmount: 2240.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BNB-774019',
            amount: 2240.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Sergio Vacaflor',
          receiverDocument: 'CI 5910283 SC',
          receiverRelationship: 'Encargado',
          capturedAt: '17:58',
        },
      },
      {
        id: 'parada-120',
        sequence: 20,
        customerName: 'Abarrotes La Esperanza',
        customerCode: 'CLI-3401',
        address: 'Av. Alemania esq. 4to Anillo',
        zoneName: 'Zona Norte - Alemania',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9060',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '10 min (2.1 km)',
        travelMinutes: 10,
        arrivedAt: '18:11',
        deliveredAt: '18:31',
        serviceDuration: '20 min',
        items: [
          {
            id: 'item-20',
            sku: 'CERV-PACE-620',
            productName: 'Cerveza Paceña Pilsener 620ml x12',
            category: 'Cervezas',
            plannedQty: 15,
            deliveredQty: 15,
            returnedQty: 0,
            unitPrice: 120.0,
            total: 1800.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104946',
            invoiceAmount: 1800.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008921',
            amount: 1800.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Esperanza Pinto',
          receiverDocument: 'CI 3819024 SC',
          receiverRelationship: 'Propietaria',
          capturedAt: '18:29',
        },
      },
    ],
  },
  {
    id: 'ot-100452',
    code: 100452,
    codeFormatted: 'OT-100452',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-20T07:00:00',
    completedDate: '2026-08-20T15:10:00',
    dateFormatted: '20/08/2026',
    dateIso: '2026-08-20',
    totalKm: 54.2,
    assignedWeightKg: 4210.0,
    assignedVolumeM3: 16.8,
    status: 'DISCREPANCY',
    statusLabel: 'Con discrepancia',
    truck: {
      id: 15,
      plate: '2489-XYZ',
      code: 'CAM-015',
      truckType: 'Furgón 6 Tn',
      isRefrigerated: false,
      capacityKg: 6000,
      capacityM3: 20.0,
    },
    driver: {
      name: 'Juan Pérez Montaño',
      phone: '+591 78901234',
      document: '4829103 SC',
    },
    helper: {
      name: 'Jorge Salces Pinto',
      phone: '+591 73491823',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 5,
      completedStops: 4,
      successRate: 80,
      totalInvoiced: 21300.0,
      totalCollected: 18100.0,
      collectedCash: 11500.0,
      collectedQr: 6600.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 490,
      driveDurationMinutes: 230,
      serviceDurationMinutes: 260,
    },
    logisticAssets: [
      {
        assetCode: 'PALLET-STD',
        assetName: 'Pallet Madera Estándar (1.20x1.00m)',
        dispatchedQty: 7,
        returnedQty: 6,
        varianceQty: -1,
        status: 'DISCREPANCY',
        notes: '1 pallet retenido en custodia en Mayorista La Casona (Vale #4401)',
      },
    ],
    paradas: [
      {
        id: 'parada-201',
        sequence: 1,
        customerName: 'Mayorista La Casona',
        customerCode: 'CLI-7120',
        address: 'Av. Brasil esq. 3er Anillo Externo',
        zoneName: 'Zona Este - Brasil',
        saleChannel: 'Mayorista',
        deliveryNoteNumber: 'REM-2026-9051',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '24 min (5.8 km)',
        travelMinutes: 24,
        arrivedAt: '07:45',
        deliveredAt: '08:40',
        serviceDuration: '55 min',
        items: [
          {
            id: 'item-201',
            sku: 'CERV-PACE-620',
            productName: 'Cerveza Paceña Pilsener 620ml x12',
            category: 'Cervezas',
            plannedQty: 60,
            deliveredQty: 60,
            returnedQty: 0,
            unitPrice: 118.0,
            total: 7080.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104940',
            invoiceAmount: 7080.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008920',
            amount: 7080.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Don Mario Justiniano',
          receiverDocument: 'CI 3109281 SC',
          receiverRelationship: 'Propietario',
          capturedAt: '08:35',
        },
      },
    ],
  },
  {
    id: 'ot-100453',
    code: 100453,
    codeFormatted: 'OT-100453',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-19T06:45:00',
    completedDate: '2026-08-19T13:30:00',
    dateFormatted: '19/08/2026',
    dateIso: '2026-08-19',
    totalKm: 38.0,
    assignedWeightKg: 2950.0,
    assignedVolumeM3: 11.2,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 18,
      plate: '1844-KLP',
      code: 'CAM-018',
      truckType: 'Furgón 4 Tn',
      isRefrigerated: false,
      capacityKg: 4000,
      capacityM3: 14.0,
    },
    driver: {
      name: 'Miguel Torrico Zeballos',
      phone: '+591 77334455',
      document: '6901923 SC',
    },
    helper: {
      name: 'David Flores Rojas',
      phone: '+591 78912304',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 4,
      completedStops: 4,
      successRate: 100,
      totalInvoiced: 16800.0,
      totalCollected: 16800.0,
      collectedCash: 8400.0,
      collectedQr: 8400.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 405,
      driveDurationMinutes: 160,
      serviceDurationMinutes: 245,
    },
    logisticAssets: [
      {
        assetCode: 'PALLET-STD',
        assetName: 'Pallet Madera Estándar (1.20x1.00m)',
        dispatchedQty: 4,
        returnedQty: 4,
        varianceQty: 0,
        status: 'RETURNED_OK',
      },
    ],
    paradas: [
      {
        id: 'parada-301',
        sequence: 1,
        customerName: 'Supermercados Tía Santos Dumont',
        customerCode: 'CLI-8098',
        address: 'Av. Santos Dumont esq. 4to Anillo',
        zoneName: 'Zona Sur - Santos Dumont',
        saleChannel: 'Supermercado',
        deliveryNoteNumber: 'REM-2026-8910',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '22 min (5.0 km)',
        travelMinutes: 22,
        arrivedAt: '07:20',
        deliveredAt: '08:10',
        serviceDuration: '50 min',
        items: [
          {
            id: 'item-301',
            sku: 'CERV-PACE-620',
            productName: 'Cerveza Paceña Pilsener 620ml x12',
            category: 'Cervezas',
            plannedQty: 30,
            deliveredQty: 30,
            returnedQty: 0,
            unitPrice: 120.0,
            total: 3600.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104880',
            invoiceAmount: 3600.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BMSC-330192',
            amount: 3600.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Hernán Saucedo',
          receiverDocument: 'CI 4019283 SC',
          receiverRelationship: 'Jefe de Tienda',
          capturedAt: '08:05',
        },
      },
    ],
  },
  {
    id: 'ot-100454',
    code: 100454,
    codeFormatted: 'OT-100454',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-18T06:30:00',
    completedDate: '2026-08-18T16:00:00',
    dateFormatted: '18/08/2026',
    dateIso: '2026-08-18',
    totalKm: 62.1,
    assignedWeightKg: 5200.0,
    assignedVolumeM3: 19.5,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 20,
      plate: '4120-NMK',
      code: 'CAM-020',
      truckType: 'Furgón 7 Tn',
      isRefrigerated: true,
      capacityKg: 7000,
      capacityM3: 22.0,
    },
    driver: {
      name: 'Fernando Áñez Hurtado',
      phone: '+591 76019283',
      document: '3819023 SC',
    },
    helper: {
      name: 'Sergio Morales Claros',
      phone: '+591 77481920',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 5,
      completedStops: 5,
      successRate: 100,
      totalInvoiced: 34900.0,
      totalCollected: 34900.0,
      collectedCash: 16500.0,
      collectedQr: 10400.0,
      collectedTransfer: 8000.0,
      totalDurationMinutes: 570,
      driveDurationMinutes: 260,
      serviceDurationMinutes: 310,
    },
    logisticAssets: [
      {
        assetCode: 'PALLET-STD',
        assetName: 'Pallet Madera Estándar (1.20x1.00m)',
        dispatchedQty: 8,
        returnedQty: 8,
        varianceQty: 0,
        status: 'RETURNED_OK',
      },
    ],
    paradas: [],
  },
  {
    id: 'ot-100455',
    code: 100455,
    codeFormatted: 'OT-100455',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-17T07:15:00',
    completedDate: '2026-08-17T14:20:00',
    dateFormatted: '17/08/2026',
    dateIso: '2026-08-17',
    totalKm: 41.5,
    assignedWeightKg: 3100.0,
    assignedVolumeM3: 12.0,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 22,
      plate: '5021-PQR',
      code: 'CAM-022',
      truckType: 'Furgón 4.5 Tn',
      isRefrigerated: false,
      capacityKg: 4500,
      capacityM3: 15.0,
    },
    driver: {
      name: 'Pedro Morales Cuéllar',
      phone: '+591 71092834',
      document: '4910294 SC',
    },
    helper: {
      name: 'Esteban Paz Rivero',
      phone: '+591 78192039',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 4,
      completedStops: 4,
      successRate: 100,
      totalInvoiced: 19400.0,
      totalCollected: 19400.0,
      collectedCash: 12400.0,
      collectedQr: 7000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 425,
      driveDurationMinutes: 180,
      serviceDurationMinutes: 245,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100450',
    code: 100450,
    codeFormatted: 'OT-100450',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-16T06:30:00',
    completedDate: '2026-08-16T13:45:00',
    dateFormatted: '16/08/2026',
    dateIso: '2026-08-16',
    totalKm: 35.8,
    assignedWeightKg: 2800.0,
    assignedVolumeM3: 10.5,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 12,
      plate: '3012-ABC',
      code: 'CAM-012',
      truckType: 'Furgón 5 Tn',
      isRefrigerated: true,
      capacityKg: 5000,
      capacityM3: 18.0,
    },
    driver: {
      name: 'Carlos Mendoza Vargas',
      phone: '+591 76543210',
      document: '5498214 SC',
    },
    helper: {
      name: 'Roberto Quispe Lima',
      phone: '+591 71239845',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 5,
      completedStops: 5,
      successRate: 100,
      totalInvoiced: 22100.0,
      totalCollected: 22100.0,
      collectedCash: 11000.0,
      collectedQr: 8100.0,
      collectedTransfer: 3000.0,
      totalDurationMinutes: 435,
      driveDurationMinutes: 190,
      serviceDurationMinutes: 245,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100449',
    code: 100449,
    codeFormatted: 'OT-100449',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-15T07:00:00',
    completedDate: '2026-08-15T15:30:00',
    dateFormatted: '15/08/2026',
    dateIso: '2026-08-15',
    totalKm: 51.4,
    assignedWeightKg: 4600.0,
    assignedVolumeM3: 17.2,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 15,
      plate: '2489-XYZ',
      code: 'CAM-015',
      truckType: 'Furgón 6 Tn',
      isRefrigerated: false,
      capacityKg: 6000,
      capacityM3: 20.0,
    },
    driver: {
      name: 'Juan Pérez Montaño',
      phone: '+591 78901234',
      document: '4829103 SC',
    },
    helper: {
      name: 'Jorge Salces Pinto',
      phone: '+591 73491823',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 6,
      completedStops: 6,
      successRate: 100,
      totalInvoiced: 31200.0,
      totalCollected: 31200.0,
      collectedCash: 18000.0,
      collectedQr: 13200.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 510,
      driveDurationMinutes: 220,
      serviceDurationMinutes: 290,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100448',
    code: 100448,
    codeFormatted: 'OT-100448',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-14T06:45:00',
    completedDate: '2026-08-14T14:15:00',
    dateFormatted: '14/08/2026',
    dateIso: '2026-08-14',
    totalKm: 44.0,
    assignedWeightKg: 3500.0,
    assignedVolumeM3: 13.8,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 18,
      plate: '1844-KLP',
      code: 'CAM-018',
      truckType: 'Furgón 4 Tn',
      isRefrigerated: false,
      capacityKg: 4000,
      capacityM3: 14.0,
    },
    driver: {
      name: 'Miguel Torrico Zeballos',
      phone: '+591 77334455',
      document: '6901923 SC',
    },
    helper: {
      name: 'David Flores Rojas',
      phone: '+591 78912304',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 5,
      completedStops: 5,
      successRate: 100,
      totalInvoiced: 24500.0,
      totalCollected: 24500.0,
      collectedCash: 14000.0,
      collectedQr: 10500.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 450,
      driveDurationMinutes: 195,
      serviceDurationMinutes: 255,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100447',
    code: 100447,
    codeFormatted: 'OT-100447',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-13T07:15:00',
    completedDate: '2026-08-13T16:00:00',
    dateFormatted: '13/08/2026',
    dateIso: '2026-08-13',
    totalKm: 58.2,
    assignedWeightKg: 4900.0,
    assignedVolumeM3: 18.4,
    status: 'DISCREPANCY',
    statusLabel: 'Con discrepancia',
    truck: {
      id: 20,
      plate: '4120-NMK',
      code: 'CAM-020',
      truckType: 'Furgón 7 Tn',
      isRefrigerated: true,
      capacityKg: 7000,
      capacityM3: 22.0,
    },
    driver: {
      name: 'Fernando Áñez Hurtado',
      phone: '+591 76019283',
      document: '3819023 SC',
    },
    helper: {
      name: 'Sergio Morales Claros',
      phone: '+591 77481920',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 6,
      completedStops: 5,
      successRate: 83.3,
      totalInvoiced: 29800.0,
      totalCollected: 26100.0,
      collectedCash: 15000.0,
      collectedQr: 11100.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 525,
      driveDurationMinutes: 240,
      serviceDurationMinutes: 285,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100446',
    code: 100446,
    codeFormatted: 'OT-100446',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-12T06:30:00',
    completedDate: '2026-08-12T13:50:00',
    dateFormatted: '12/08/2026',
    dateIso: '2026-08-12',
    totalKm: 39.4,
    assignedWeightKg: 3200.0,
    assignedVolumeM3: 12.6,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 22,
      plate: '5021-PQR',
      code: 'CAM-022',
      truckType: 'Furgón 4.5 Tn',
      isRefrigerated: false,
      capacityKg: 4500,
      capacityM3: 15.0,
    },
    driver: {
      name: 'Pedro Morales Cuéllar',
      phone: '+591 71092834',
      document: '4910294 SC',
    },
    helper: {
      name: 'Esteban Paz Rivero',
      phone: '+591 78192039',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 4,
      completedStops: 4,
      successRate: 100,
      totalInvoiced: 20100.0,
      totalCollected: 20100.0,
      collectedCash: 12100.0,
      collectedQr: 8000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 440,
      driveDurationMinutes: 185,
      serviceDurationMinutes: 255,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100445',
    code: 100445,
    codeFormatted: 'OT-100445',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-11T06:45:00',
    completedDate: '2026-08-11T14:30:00',
    dateFormatted: '11/08/2026',
    dateIso: '2026-08-11',
    totalKm: 42.1,
    assignedWeightKg: 3600.0,
    assignedVolumeM3: 14.1,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 12,
      plate: '3012-ABC',
      code: 'CAM-012',
      truckType: 'Furgón 5 Tn',
      isRefrigerated: true,
      capacityKg: 5000,
      capacityM3: 18.0,
    },
    driver: {
      name: 'Carlos Mendoza Vargas',
      phone: '+591 76543210',
      document: '5498214 SC',
    },
    helper: {
      name: 'Roberto Quispe Lima',
      phone: '+591 71239845',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 5,
      completedStops: 5,
      successRate: 100,
      totalInvoiced: 25400.0,
      totalCollected: 25400.0,
      collectedCash: 15400.0,
      collectedQr: 10000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 465,
      driveDurationMinutes: 195,
      serviceDurationMinutes: 270,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100444',
    code: 100444,
    codeFormatted: 'OT-100444',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-10T07:00:00',
    completedDate: '2026-08-10T15:45:00',
    dateFormatted: '10/08/2026',
    dateIso: '2026-08-10',
    totalKm: 55.0,
    assignedWeightKg: 4400.0,
    assignedVolumeM3: 16.9,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 15,
      plate: '2489-XYZ',
      code: 'CAM-015',
      truckType: 'Furgón 6 Tn',
      isRefrigerated: false,
      capacityKg: 6000,
      capacityM3: 20.0,
    },
    driver: {
      name: 'Juan Pérez Montaño',
      phone: '+591 78901234',
      document: '4829103 SC',
    },
    helper: {
      name: 'Jorge Salces Pinto',
      phone: '+591 73491823',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 6,
      completedStops: 6,
      successRate: 100,
      totalInvoiced: 30500.0,
      totalCollected: 30500.0,
      collectedCash: 17500.0,
      collectedQr: 13000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 525,
      driveDurationMinutes: 235,
      serviceDurationMinutes: 290,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100443',
    code: 100443,
    codeFormatted: 'OT-100443',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-08T06:30:00',
    completedDate: '2026-08-08T13:40:00',
    dateFormatted: '08/08/2026',
    dateIso: '2026-08-08',
    totalKm: 36.2,
    assignedWeightKg: 2700.0,
    assignedVolumeM3: 10.2,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 18,
      plate: '1844-KLP',
      code: 'CAM-018',
      truckType: 'Furgón 4 Tn',
      isRefrigerated: false,
      capacityKg: 4000,
      capacityM3: 14.0,
    },
    driver: {
      name: 'Miguel Torrico Zeballos',
      phone: '+591 77334455',
      document: '6901923 SC',
    },
    helper: {
      name: 'David Flores Rojas',
      phone: '+591 78912304',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 4,
      completedStops: 4,
      successRate: 100,
      totalInvoiced: 17900.0,
      totalCollected: 17900.0,
      collectedCash: 10900.0,
      collectedQr: 7000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 430,
      driveDurationMinutes: 180,
      serviceDurationMinutes: 250,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100442',
    code: 100442,
    codeFormatted: 'OT-100442',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-07T07:15:00',
    completedDate: '2026-08-07T16:10:00',
    dateFormatted: '07/08/2026',
    dateIso: '2026-08-07',
    totalKm: 60.5,
    assignedWeightKg: 5100.0,
    assignedVolumeM3: 19.1,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 20,
      plate: '4120-NMK',
      code: 'CAM-020',
      truckType: 'Furgón 7 Tn',
      isRefrigerated: true,
      capacityKg: 7000,
      capacityM3: 22.0,
    },
    driver: {
      name: 'Fernando Áñez Hurtado',
      phone: '+591 76019283',
      document: '3819023 SC',
    },
    helper: {
      name: 'Sergio Morales Claros',
      phone: '+591 77481920',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 6,
      completedStops: 6,
      successRate: 100,
      totalInvoiced: 33800.0,
      totalCollected: 33800.0,
      collectedCash: 19800.0,
      collectedQr: 14000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 535,
      driveDurationMinutes: 250,
      serviceDurationMinutes: 285,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100441',
    code: 100441,
    codeFormatted: 'OT-100441',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-05T06:30:00',
    completedDate: '2026-08-05T14:10:00',
    dateFormatted: '05/08/2026',
    dateIso: '2026-08-05',
    totalKm: 40.0,
    assignedWeightKg: 3050.0,
    assignedVolumeM3: 11.8,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 22,
      plate: '5021-PQR',
      code: 'CAM-022',
      truckType: 'Furgón 4.5 Tn',
      isRefrigerated: false,
      capacityKg: 4500,
      capacityM3: 15.0,
    },
    driver: {
      name: 'Pedro Morales Cuéllar',
      phone: '+591 71092834',
      document: '4910294 SC',
    },
    helper: {
      name: 'Esteban Paz Rivero',
      phone: '+591 78192039',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 4,
      completedStops: 4,
      successRate: 100,
      totalInvoiced: 18500.0,
      totalCollected: 18500.0,
      collectedCash: 11500.0,
      collectedQr: 7000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 460,
      driveDurationMinutes: 190,
      serviceDurationMinutes: 270,
    },
    logisticAssets: [],
    paradas: [],
  },
]
