// Dataset enriquecido de Historial de Órdenes de Transporte (OTs).
// Estructurado según el esquema real de Base de Datos (db_script.sql):
// transport_orders, routes, trucks, delivery_orders, delivery_order_sales,
// delivery_payment_references, delivery_order_items, proof_of_deliveries, transport_order_assets.

export interface ItemEntregado {
  id: string
  sku: string
  productName: string
  category: string
  orderCode?: string
  orderType?: string
  plannedQty: number
  deliveredQty: number
  returnedQty: number
  unitPrice: number
  total: number
  rejectionReason?: string | null
}

export interface PagoCobranza {
  invoiceId: string
  invoiceAmount: number
  paymentMethod: 'CASH' | 'QR' | 'TRANSFER' | 'CHECK'
  paymentMethodLabel: string
  referenceNumber: string
  amount: number
  currency: string
  status: 'COMPLETED' | 'PENDING'
  notes?: string
}

export interface FotoEvidencia {
  id: string
  title: string
  category: 'FIRMA' | 'CARGA' | 'DOCUMENTO' | 'FACHADA' | 'COMPROBANTE'
  categoryLabel: string
  url?: string
  timestamp: string
  description?: string
  deviceInfo?: string
  coordinates?: string
}

export interface EvidenciaEntrega {
  receiverName: string
  receiverDocument: string
  receiverRelationship: string
  signatureUrl?: string
  signatureHash?: string
  photoUrl?: string
  capturedAt: string
  coordinates?: string
  gpsAccuracy?: string
  photos?: FotoEvidencia[]
}

export interface ParadaHistorial {
  id: string
  sequence: number
  customerName: string
  customerCode: string
  address: string
  zoneName: string
  saleChannel: string
  deliveryNoteNumber: string
  status: 'DELIVERED' | 'PARTIALLY_REJECTED' | 'REJECTED'
  resultCode: 'EXITOSO' | 'RECHAZO_PARCIAL' | 'RECHAZO_TOTAL'
  travelTimeFromPrevious: string
  travelMinutes: number
  arrivedAt: string
  deliveredAt: string
  serviceDuration: string
  lat?: number
  lng?: number
  items: ItemEntregado[]
  payments: PagoCobranza[]
  proofOfDelivery: EvidenciaEntrega
  incident?: {
    code: string
    description: string
    severity: 'BAJA' | 'MEDIA' | 'ALTA'
  } | null
}

export interface ActivoTransporte {
  assetCode: string
  assetName: string
  dispatchedQty: number
  returnedQty: number
  varianceQty: number
  status: 'RETURNED_OK' | 'DISCREPANCY'
  notes?: string
}

export interface OrdenTransporteHistorial {
  id: string
  code: number
  codeFormatted: string
  distributorName: string
  departureDate: string
  completedDate: string
  dateFormatted: string
  dateIso: string // YYYY-MM-DD para filtrado exacto
  totalKm: number
  assignedWeightKg: number
  assignedVolumeM3: number
  status: 'COMPLETED' | 'CHECKED_OK' | 'DISCREPANCY' | 'ENROUTE'
  statusLabel: string
  truck: {
    id: number
    plate: string
    code: string
    truckType: string
    isRefrigerated: boolean
    capacityKg: number
    capacityM3: number
  }
  driver: {
    name: string
    phone: string
    document: string
  }
  helper: {
    name: string
    phone: string
  }
  supervisor: {
    name: string
  }
  kpis: {
    totalStops: number
    completedStops: number
    successRate: number
    totalInvoiced: number
    totalCollected: number
    collectedCash: number
    collectedQr: number
    collectedTransfer: number
    collectedCheck?: number
    totalDurationMinutes: number
    driveDurationMinutes: number
    serviceDurationMinutes: number
  }
  logisticAssets: ActivoTransporte[]
  paradas: ParadaHistorial[]
}

export const HISTORIAL_ORDENES_TRANSPORTE: OrdenTransporteHistorial[] = [
  {
    id: 'ot-100451',
    code: 100451,
    codeFormatted: 'OT-100451',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-20T06:30:00',
    completedDate: '2026-08-20T14:45:00',
    dateFormatted: '20/08/2026',
    dateIso: '2026-08-20',
    totalKm: 48.5,
    assignedWeightKg: 3820.0,
    assignedVolumeM3: 15.4,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 12,
      plate: '3012-ABC',
      code: 'CAM-012',
      truckType: 'Furgón 5 Tn',
      isRefrigerated: true,
      capacityKg: 5000,
      capacityM3: 18.0,
    },
    driver: {
      name: 'Carlos Mendoza Vargas',
      phone: '+591 76543210',
      document: '5498214 SC',
    },
    helper: {
      name: 'Roberto Quispe Lima',
      phone: '+591 71239845',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 12,
      completedStops: 12,
      successRate: 100,
      totalInvoiced: 52400.0,
      totalCollected: 51656.0,
      collectedCash: 8551.0,
      collectedQr: 16655.0,
      collectedTransfer: 16950.0,
      collectedCheck: 9500.0,
      totalDurationMinutes: 630,
      driveDurationMinutes: 240,
      serviceDurationMinutes: 390,
    },
    logisticAssets: [
      {
        assetCode: 'PALLET-STD',
        assetName: 'Pallet Madera Estándar (1.20x1.00m)',
        dispatchedQty: 8,
        returnedQty: 8,
        varianceQty: 0,
        status: 'RETURNED_OK',
      },
      {
        assetCode: 'JABA-VERDE',
        assetName: 'Canastilla Plástica Reforzada',
        dispatchedQty: 60,
        returnedQty: 60,
        varianceQty: 0,
        status: 'RETURNED_OK',
      },
      {
        assetCode: 'CART-300KG',
        assetName: 'Carrito de Carga 2 Ruedas',
        dispatchedQty: 1,
        returnedQty: 1,
        varianceQty: 0,
        status: 'RETURNED_OK',
      },
    ],
    paradas: [
      {
        id: 'parada-101',
        sequence: 1,
        customerName: 'Supermercado Fidalga Equipetrol',
        customerCode: 'CLI-8092',
        address: 'Av. San Martín esq. Calle 7 Este',
        zoneName: 'Zona Norte - Equipetrol',
        saleChannel: 'Supermercado',
        deliveryNoteNumber: 'REM-2026-9041',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '18 min (4.2 km)',
        travelMinutes: 18,
        arrivedAt: '07:15',
        deliveredAt: '07:45',
        serviceDuration: '30 min',
        items: [
          {
            id: 'item-1',
            sku: 'VEN-MAY-GALON',
            productName: 'Mayonesa Kris Galón 3.8L Caja x4',
            category: 'Salsas',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 20,
            deliveredQty: 20,
            returnedQty: 0,
            unitPrice: 130.0,
            total: 2600.0,
          },
          {
            id: 'item-1b',
            sku: 'VEN-KET-GALON',
            productName: 'Ketchup Kris Galón 4kg Caja x4',
            category: 'Salsas',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 15,
            deliveredQty: 15,
            returnedQty: 0,
            unitPrice: 165.0,
            total: 2475.0,
          },
          {
            id: 'item-1c',
            sku: 'VEN-MOS-DOY-850',
            productName: 'Mostaza Kris Doypack 850g x12',
            category: 'Salsas',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 195.0,
            total: 1950.0,
          },
          {
            id: 'item-1d',
            sku: 'VEN-GOLF-DOY',
            productName: 'Salsa Golf Kris Doypack 900g x12',
            category: 'Salsas',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 8,
            deliveredQty: 8,
            returnedQty: 0,
            unitPrice: 210.0,
            total: 1680.0,
          },
          {
            id: 'item-1e',
            sku: 'VEN-LLAJ-200',
            productName: 'Llajua con Quirquiña Kris Doypack 200g x24',
            category: 'Culinarios',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 12,
            deliveredQty: 12,
            returnedQty: 0,
            unitPrice: 140.0,
            total: 1680.0,
          },
          {
            id: 'item-1f',
            sku: 'VEN-ATUN-ACE-24',
            productName: 'Atún en Aceite Vegetal Kris x24 Latas',
            category: 'Conservas',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 195.0,
            total: 1950.0,
          },
          {
            id: 'item-1g',
            sku: 'VEN-SARD-TOM-24',
            productName: 'Sardinas en Salsa de Tomate Kris x24 Latas',
            category: 'Conservas',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 6,
            deliveredQty: 6,
            returnedQty: 0,
            unitPrice: 160.0,
            total: 960.0,
          },
          {
            id: 'item-1h',
            sku: 'VEN-CALD-GAL-24',
            productName: 'Caldo Concentrado de Gallina Kris x24 Cubos',
            category: 'Caldos y Sopas',
            orderCode: 'PED-2026-8801',
            orderType: 'Preventa Regular',
            plannedQty: 15,
            deliveredQty: 15,
            returnedQty: 0,
            unitPrice: 28.0,
            total: 420.0,
          },
          {
            id: 'item-1i',
            sku: 'VEN-FRUS-DUR-2L',
            productName: 'Jugo Frussion Durazno con Pulpa 2L Pack x6',
            category: 'Bebidas Líquidas',
            orderCode: 'PED-2026-8804',
            orderType: 'Recarga Urgente',
            plannedQty: 12,
            deliveredQty: 12,
            returnedQty: 0,
            unitPrice: 58.0,
            total: 696.0,
          },
          {
            id: 'item-1j',
            sku: 'VEN-FRUS-NAR-1L',
            productName: 'Jugo Frussion Naranja Néctar 1L x12',
            category: 'Bebidas Líquidas',
            orderCode: 'PED-2026-8804',
            orderType: 'Recarga Urgente',
            plannedQty: 8,
            deliveredQty: 8,
            returnedQty: 0,
            unitPrice: 72.0,
            total: 576.0,
          },
          {
            id: 'item-1k',
            sku: 'VEN-AGUA-SPER-2L',
            productName: 'Agua Purificada Speranza 2L Sin Gas Pack x6',
            category: 'Aguas',
            orderCode: 'PED-2026-8804',
            orderType: 'Recarga Urgente',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 32.0,
            total: 320.0,
          },
          {
            id: 'item-1l',
            sku: 'VEN-ENERG-RAPTOR',
            productName: 'Energizante Raptor 500ml Pack x12',
            category: 'Energizantes',
            orderCode: 'PED-2026-8804',
            orderType: 'Recarga Urgente',
            plannedQty: 6,
            deliveredQty: 6,
            returnedQty: 0,
            unitPrice: 78.0,
            total: 468.0,
          },
          {
            id: 'item-1m',
            sku: 'VEN-KRIS-800',
            productName: 'Achocolatado Kriskao Clásico Bolsa 800g x12',
            category: 'Modificadores de Leche',
            orderCode: 'PED-2026-8804',
            orderType: 'Recarga Urgente',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 95.0,
            total: 950.0,
          },
          {
            id: 'item-1n',
            sku: 'VEN-LEV-SECA-500',
            productName: 'Levadura Seca Instantánea FACRULESA 500g x20',
            category: 'Panificación',
            orderCode: 'PED-2026-8804',
            orderType: 'Recarga Urgente',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 280.0,
            total: 560.0,
          },
          {
            id: 'item-1o',
            sku: 'VEN-CER-AZU-400',
            productName: 'Cereal Azucaraditas Kris Doypack 400g x12',
            category: 'Cereales',
            orderCode: 'PED-2026-8809',
            orderType: 'Promoción Especial',
            plannedQty: 4,
            deliveredQty: 4,
            returnedQty: 0,
            unitPrice: 85.0,
            total: 340.0,
          },
          {
            id: 'item-1p',
            sku: 'VEN-CER-CHOCO-400',
            productName: 'Cereal Chocoexplosión Kris Doypack 400g x12',
            category: 'Cereales',
            orderCode: 'PED-2026-8809',
            orderType: 'Promoción Especial',
            plannedQty: 4,
            deliveredQty: 4,
            returnedQty: 0,
            unitPrice: 88.0,
            total: 352.0,
          },
          {
            id: 'item-1q',
            sku: 'VEN-GEL-FRUT-12',
            productName: 'Gelatina Kris Frutilla Pack x24 Bolsas',
            category: 'Postres',
            orderCode: 'PED-2026-8809',
            orderType: 'Promoción Especial',
            plannedQty: 4,
            deliveredQty: 4,
            returnedQty: 0,
            unitPrice: 48.0,
            total: 192.0,
          },
          {
            id: 'item-1r',
            sku: 'VEN-FLAN-VAIN-12',
            productName: 'Flan Vainilla Kris Pack x24',
            category: 'Postres',
            orderCode: 'PED-2026-8809',
            orderType: 'Promoción Especial',
            plannedQty: 3,
            deliveredQty: 3,
            returnedQty: 0,
            unitPrice: 45.0,
            total: 135.0,
          },
          {
            id: 'item-1s',
            sku: 'VEN-LAV-BRIS-2L',
            productName: 'Lavandina Bristar Tradicional 2L Pack x6',
            category: 'Limpieza del Hogar',
            orderCode: 'PED-2026-8809',
            orderType: 'Promoción Especial',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 48.0,
            total: 96.0,
          },
          {
            id: 'item-1t',
            sku: 'VEN-JAB-SHAB-1L',
            productName: 'Jabón Líquido Antibacterial Shabay 1L Dosificador',
            category: 'Higiene Personal',
            orderCode: 'PED-2026-8809',
            orderType: 'Promoción Especial',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 25.0,
            total: 50.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104928',
            invoiceAmount: 18450.0,
            paymentMethod: 'TRANSFER',
            paymentMethodLabel: 'Transferencia BNB',
            referenceNumber: 'TRF-BNB-994821',
            amount: 8000.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104928',
            invoiceAmount: 18450.0,
            paymentMethod: 'CHECK',
            paymentMethodLabel: 'Cheque Banco Mercantil',
            referenceNumber: 'CHQ-BMSC-40912',
            amount: 5000.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104928',
            invoiceAmount: 18450.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BMSC-110294',
            amount: 3000.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104928',
            invoiceAmount: 18450.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008901',
            amount: 2450.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Lic. Mariana Justiniano',
          receiverDocument: 'CI 4598122 SC',
          receiverRelationship: 'Encargada de Recepción y Almacén',
          capturedAt: '2026-08-21 07:44:12',
          coordinates: '-17.77892, -63.19012 (Av. San Martín esq. Calle 7)',
          gpsAccuracy: '± 3.8 metros (GPS Verificado)',
          signatureHash: 'SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
          signatureUrl: 'data:image/svg+xml;utf8,<svg ... />',
          photos: [
            {
              id: 'evid-1',
              title: 'Firma Digital de Recepción',
              category: 'FIRMA',
              categoryLabel: 'Firma del Receptor',
              timestamp: '07:44:12',
              coordinates: '-17.77892, -63.19012',
              deviceInfo: 'Handheld Zebra TC26 · Android 12',
              description: 'Firma digital de recepción capturada en pantalla táctil con validación de hora y geolocalización en punto.',
            },
            {
              id: 'evid-2',
              title: 'Fotografía de la Entrega',
              category: 'CARGA',
              categoryLabel: 'Fotografía de Entrega',
              timestamp: '07:42:05',
              coordinates: '-17.77891, -63.19015',
              deviceInfo: 'Cámara trasera 13MP Zebra TC26',
              description: 'Fotografía de la mercadería entregada y descargada en el almacén del cliente en perfecto estado.',
            },
          ],
        },
      },
      {
        id: 'parada-102',
        sequence: 2,
        customerName: 'Abarrotes & Licorería Don Carlos',
        customerCode: 'CLI-5531',
        address: 'Av. Busch esq. 3er Anillo Interno',
        zoneName: 'Zona Oeste - Busch',
        saleChannel: 'Tradicional',
        deliveryNoteNumber: 'REM-2026-9042',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '14 min (3.1 km)',
        travelMinutes: 14,
        arrivedAt: '08:00',
        deliveredAt: '08:25',
        serviceDuration: '25 min',
        items: [
          {
            id: 'item-2',
            sku: 'VEN-MAY-DOY-900',
            productName: 'Mayonesa Kris Doypack 900g x12',
            category: 'Salsas',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 190.0,
            total: 1900.0,
          },
          {
            id: 'item-2b',
            sku: 'VEN-KET-DOY-850',
            productName: 'Ketchup Kris Doypack 850g x12',
            category: 'Salsas',
            plannedQty: 5,
            deliveredQty: 5,
            returnedQty: 0,
            unitPrice: 160.0,
            total: 800.0,
          },
          {
            id: 'item-2c',
            sku: 'VEN-MOS-DOY-850',
            productName: 'Mostaza Kris Doypack 850g x12',
            category: 'Salsas',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 200.0,
            total: 400.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104929',
            invoiceAmount: 3100.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BMSC-883109',
            amount: 3100.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Carlos Gutiérrez Aguilera',
          receiverDocument: 'CI 3829104 SC',
          receiverRelationship: 'Propietario',
          capturedAt: '08:22',
        },
      },
      {
        id: 'parada-103',
        sequence: 3,
        customerName: 'Micromercado El Triunfo',
        customerCode: 'CLI-4120',
        address: 'Calle Libertad #420 (Casco Viejo)',
        zoneName: 'Zona Centro',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9043',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '12 min (2.8 km)',
        travelMinutes: 12,
        arrivedAt: '08:38',
        deliveredAt: '09:00',
        serviceDuration: '22 min',
        items: [
          {
            id: 'item-3',
            sku: 'VEN-FRUS-DUR-2L',
            productName: 'Jugo Frussion Durazno con Pulpa 2L x6',
            category: 'Bebidas Líquidas',
            plannedQty: 25,
            deliveredQty: 25,
            returnedQty: 0,
            unitPrice: 58.0,
            total: 1450.0,
          },
          {
            id: 'item-3b',
            sku: 'VEN-KRIS-800',
            productName: 'Achocolatado Kriskao Clásico Bolsa 800g x12',
            category: 'Modificadores de Leche',
            plannedQty: 20,
            deliveredQty: 20,
            returnedQty: 0,
            unitPrice: 32.0,
            total: 640.0,
          },
          {
            id: 'item-3c',
            sku: 'VEN-GEL-FRUT-12',
            productName: 'Gelatina Kris Frutilla Pack x12',
            category: 'Postres',
            plannedQty: 8,
            deliveredQty: 8,
            returnedQty: 0,
            unitPrice: 39.25,
            total: 314.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104930',
            invoiceAmount: 2404.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008912',
            amount: 1404.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104930',
            invoiceAmount: 2404.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple BCP',
            referenceNumber: 'QR-BCP-774102',
            amount: 1000.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Teresa Ramos',
          receiverDocument: 'CI 2948102 SC',
          receiverRelationship: 'Administradora',
          capturedAt: '08:58',
        },
      },
      {
        id: 'parada-104',
        sequence: 4,
        customerName: 'Comercializadora San Roque',
        customerCode: 'CLI-9921',
        address: 'Av. Grigotá esq. 2do Anillo',
        zoneName: 'Zona Sur - La Ramada',
        saleChannel: 'Mayorista',
        deliveryNoteNumber: 'REM-2026-9044',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '16 min (3.5 km)',
        travelMinutes: 16,
        arrivedAt: '09:18',
        deliveredAt: '09:48',
        serviceDuration: '30 min',
        items: [
          {
            id: 'item-4',
            sku: 'VEN-MAY-GALON',
            productName: 'Mayonesa Kris Galón 3.8L Caja x4',
            category: 'Salsas',
            plannedQty: 25,
            deliveredQty: 25,
            returnedQty: 0,
            unitPrice: 170.0,
            total: 4250.0,
          },
          {
            id: 'item-4b',
            sku: 'VEN-KET-GALON',
            productName: 'Ketchup Kris Galón 4kg Caja x4',
            category: 'Salsas',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 165.0,
            total: 1650.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104931',
            invoiceAmount: 5900.0,
            paymentMethod: 'TRANSFER',
            paymentMethodLabel: 'Transferencia Banco Ganadero',
            referenceNumber: 'TRF-BGA-440192',
            amount: 3000.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104931',
            invoiceAmount: 5900.0,
            paymentMethod: 'CHECK',
            paymentMethodLabel: 'Cheque Banco Mercantil',
            referenceNumber: 'CHQ-BMSC-88102',
            amount: 1900.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104931',
            invoiceAmount: 5900.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple BNB',
            referenceNumber: 'QR-BNB-339102',
            amount: 1000.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Gonzalo Peñaranda',
          receiverDocument: 'CI 4892011 SC',
          receiverRelationship: 'Jefe de Almacén',
          capturedAt: '09:45',
        },
      },
      {
        id: 'parada-105',
        sequence: 5,
        customerName: 'Hipermaxi Los Pozos',
        customerCode: 'CLI-8095',
        address: 'Av. Aroma esq. 6 de Agosto',
        zoneName: 'Zona Este - Los Pozos',
        saleChannel: 'Supermercado',
        deliveryNoteNumber: 'REM-2026-9045',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '15 min (3.0 km)',
        travelMinutes: 15,
        arrivedAt: '10:05',
        deliveredAt: '10:35',
        serviceDuration: '30 min',
        items: [
          {
            id: 'item-5',
            sku: 'VEN-ATUN-ACE-24',
            productName: 'Atún en Aceite Vegetal Kris x24 Latas',
            category: 'Conservas',
            plannedQty: 15,
            deliveredQty: 15,
            returnedQty: 0,
            unitPrice: 195.0,
            total: 2925.0,
          },
          {
            id: 'item-5b',
            sku: 'VEN-CER-AZU-400',
            productName: 'Cereal Azucaraditas Kris Doypack 400g x12',
            category: 'Cereales',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 187.0,
            total: 1870.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104932',
            invoiceAmount: 4795.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BCP-772910',
            amount: 4795.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Víctor Hugo Claros',
          receiverDocument: 'CI 6029311 SC',
          receiverRelationship: 'Supervisor de Plataforma',
          capturedAt: '10:32',
        },
      },
      {
        id: 'parada-106',
        sequence: 6,
        customerName: 'Pulpería La Tradición',
        customerCode: 'CLI-3180',
        address: 'Av. Virgen de Cotoca esq. 4to Anillo',
        zoneName: 'Zona Pampa de la Isla',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9046',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '12 min (2.5 km)',
        travelMinutes: 12,
        arrivedAt: '10:50',
        deliveredAt: '11:10',
        serviceDuration: '20 min',
        items: [
          {
            id: 'item-6',
            sku: 'VEN-REFR-POL-NAR',
            productName: 'Refresco en Polvo Kris Naranja Pack x24',
            category: 'Bebidas en Polvo',
            plannedQty: 8,
            deliveredQty: 8,
            returnedQty: 0,
            unitPrice: 36.0,
            total: 288.0,
          },
          {
            id: 'item-6b',
            sku: 'VEN-POLV-HORN-450',
            productName: 'Polvo para Hornear Kris Lata 450g x12',
            category: 'Panificación',
            plannedQty: 1,
            deliveredQty: 1,
            returnedQty: 0,
            unitPrice: 232.0,
            total: 232.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104933',
            invoiceAmount: 520.0,
            paymentMethod: 'TRANSFER',
            paymentMethodLabel: 'Transferencia Banco Bisa',
            referenceNumber: 'TRF-BISA-551029',
            amount: 300.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104933',
            invoiceAmount: 520.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008914',
            amount: 220.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Rosario Salvatierra',
          receiverDocument: 'CI 3901923 SC',
          receiverRelationship: 'Propietaria',
          capturedAt: '11:08',
        },
      },
      {
        id: 'parada-107',
        sequence: 7,
        customerName: 'Tienda Doña Carmen',
        customerCode: 'CLI-2201',
        address: 'Calle 10 de Agosto #84',
        zoneName: 'Zona Pampa de la Isla',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9047',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '8 min (1.4 km)',
        travelMinutes: 8,
        arrivedAt: '11:20',
        deliveredAt: '11:35',
        serviceDuration: '15 min',
        items: [
          {
            id: 'item-7',
            sku: 'VEN-FRUS-NAR-1L',
            productName: 'Jugo Frussion Naranja Néctar 1L x12',
            category: 'Bebidas Líquidas',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 72.0,
            total: 720.0,
          },
          {
            id: 'item-7b',
            sku: 'VEN-AGUA-SPER-2L',
            productName: 'Agua Purificada Speranza 2L Pack x6',
            category: 'Aguas',
            plannedQty: 11,
            deliveredQty: 11,
            returnedQty: 0,
            unitPrice: 32.0,
            total: 352.0,
          },
          {
            id: 'item-7c',
            sku: 'VEN-CALD-GAL-24',
            productName: 'Caldo Concentrado de Gallina Kris x24 Cubos',
            category: 'Caldos y Sopas',
            plannedQty: 5,
            deliveredQty: 5,
            returnedQty: 0,
            unitPrice: 30.0,
            total: 150.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104934',
            invoiceAmount: 1222.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple BNB',
            referenceNumber: 'QR-BNB-338210',
            amount: 600.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104934',
            invoiceAmount: 1222.0,
            paymentMethod: 'TRANSFER',
            paymentMethodLabel: 'Transferencia Banco Ganadero',
            referenceNumber: 'TRF-BGA-882014',
            amount: 400.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104934',
            invoiceAmount: 1222.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008940',
            amount: 222.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Carmen Ortiz',
          receiverDocument: 'CI 5019283 SC',
          receiverRelationship: 'Dueña',
          capturedAt: '11:33',
        },
      },
      {
        id: 'parada-108',
        sequence: 8,
        customerName: 'Licorería El Trébol',
        customerCode: 'CLI-5502',
        address: 'Av. Cumavi esq. 3er Anillo',
        zoneName: 'Zona Villa 1ro de Mayo',
        saleChannel: 'Tradicional',
        deliveryNoteNumber: 'REM-2026-9048',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '12 min (2.9 km)',
        travelMinutes: 12,
        arrivedAt: '11:48',
        deliveredAt: '12:08',
        serviceDuration: '20 min',
        items: [
          {
            id: 'item-8',
            sku: 'VEN-ENERG-RAPTOR',
            productName: 'Energizante Raptor 500ml Pack x12',
            category: 'Energizantes',
            plannedQty: 20,
            deliveredQty: 20,
            returnedQty: 0,
            unitPrice: 78.0,
            total: 1560.0,
          },
          {
            id: 'item-8b',
            sku: 'VEN-CHICH-CAM-2L',
            productName: 'Chicha Camba Tradicional 2L Pack x6',
            category: 'Bebidas Típicas',
            plannedQty: 20,
            deliveredQty: 20,
            returnedQty: 0,
            unitPrice: 45.0,
            total: 900.0,
          },
          {
            id: 'item-8c',
            sku: 'VEN-AGUA-SPER-500',
            productName: 'Agua Purificada Speranza 500ml Pack x12',
            category: 'Aguas',
            plannedQty: 25,
            deliveredQty: 25,
            returnedQty: 0,
            unitPrice: 25.60,
            total: 640.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104935',
            invoiceAmount: 3100.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008915',
            amount: 3100.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Marcos Terrazas',
          receiverDocument: 'CI 4109283 SC',
          receiverRelationship: 'Administrador',
          capturedAt: '12:05',
        },
      },
      {
        id: 'parada-109',
        sequence: 9,
        customerName: 'Minimarket 24/7 Radial 10',
        customerCode: 'CLI-4410',
        address: 'Av. Radial 10 esq. 4to Anillo',
        zoneName: 'Zona Sur - Radial 10',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9049',
        status: 'PARTIALLY_REJECTED',
        resultCode: 'RECHAZO_PARCIAL',
        travelTimeFromPrevious: '11 min (2.3 km)',
        travelMinutes: 11,
        arrivedAt: '12:20',
        deliveredAt: '12:45',
        serviceDuration: '25 min',
        items: [
          {
            id: 'item-9a',
            sku: 'VEN-MAY-DOY-900',
            productName: 'Mayonesa Kris Doypack 900g x12',
            category: 'Salsas',
            plannedQty: 10,
            deliveredQty: 8,
            returnedQty: 2,
            unitPrice: 120.0,
            total: 960.0,
            rejectionReason: '2 cajas con sachet roto por golpe en transporte',
          },
          {
            id: 'item-9b',
            sku: 'VEN-FRUS-MAN-2L',
            productName: 'Jugo Frussion Manzana 2L Pack x6',
            category: 'Bebidas Líquidas',
            plannedQty: 5,
            deliveredQty: 5,
            returnedQty: 0,
            unitPrice: 58.0,
            total: 290.0,
          },
          {
            id: 'item-9c',
            sku: 'VEN-ENERG-RAPTOR',
            productName: 'Energizante Raptor 500ml Pack x12',
            category: 'Energizantes',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 78.0,
            total: 156.0,
          },
          {
            id: 'item-9d',
            sku: 'VEN-LAV-BRIS-2L',
            productName: 'Lavandina Bristar Tradicional 2L Pack x6',
            category: 'Limpieza del Hogar',
            plannedQty: 8,
            deliveredQty: 8,
            returnedQty: 0,
            unitPrice: 48.0,
            total: 384.0,
          },
          {
            id: 'item-9e',
            sku: 'VEN-LAV-VAJ-BRIS',
            productName: 'Lavavajillas Limón Bristar Doypack 900ml x12',
            category: 'Limpieza del Hogar',
            plannedQty: 3,
            deliveredQty: 3,
            returnedQty: 0,
            unitPrice: 84.0,
            total: 252.0,
          },
          {
            id: 'item-9f',
            sku: 'VEN-CER-CHOCO-400',
            productName: 'Cereal Chocoexplosión Kris Doypack 400g x12',
            category: 'Cereales',
            plannedQty: 2,
            deliveredQty: 2,
            returnedQty: 0,
            unitPrice: 59.0,
            total: 118.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104936',
            invoiceAmount: 2160.0,
            paymentMethod: 'TRANSFER',
            paymentMethodLabel: 'Transferencia BNB',
            referenceNumber: 'TRF-BNB-772910',
            amount: 800.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104936',
            invoiceAmount: 2160.0,
            paymentMethod: 'CHECK',
            paymentMethodLabel: 'Cheque Banco BCP',
            referenceNumber: 'CHQ-BCP-19204',
            amount: 600.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104936',
            invoiceAmount: 2160.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BMSC-441092',
            amount: 400.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104936',
            invoiceAmount: 2160.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008960',
            amount: 360.0,
            currency: 'BOB',
            status: 'COMPLETED',
            notes: 'Descuento aplicado por 2 cajas dañadas',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Sandro Aguilera',
          receiverDocument: 'CI 4892019 SC',
          receiverRelationship: 'Encargado de Local',
          capturedAt: '12:42',
        },
        incident: {
          code: 'ROTURA_TRANSITO',
          description: 'Rechazo parcial de 2 cajas por rotura. Supervisor notificado.',
          severity: 'MEDIA',
        },
      },
      {
        id: 'parada-110',
        sequence: 10,
        customerName: 'Abarrotes Santa Rosa',
        customerCode: 'CLI-3304',
        address: 'Calle Lemoine #52',
        zoneName: 'Zona Sur - Santos Dumont',
        saleChannel: 'Horizontal',
        deliveryNoteNumber: 'REM-2026-9050',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '10 min (2.1 km)',
        travelMinutes: 10,
        arrivedAt: '12:56',
        deliveredAt: '13:16',
        serviceDuration: '20 min',
        items: [
          {
            id: 'item-10',
            sku: 'VEN-LIMP-PIS-LAV',
            productName: 'Limpiapisos Lavanda Bristar 1L x12',
            category: 'Limpieza del Hogar',
            plannedQty: 15,
            deliveredQty: 15,
            returnedQty: 0,
            unitPrice: 66.0,
            total: 990.0,
          },
          {
            id: 'item-10b',
            sku: 'VEN-AMB-FLOR-12',
            productName: 'Ambientador Floral Bristar Spray 360ml x12',
            category: 'Limpieza del Hogar',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 72.5,
            total: 725.0,
          },
          {
            id: 'item-10c',
            sku: 'VEN-JAB-SHAB-1L',
            productName: 'Jabón Líquido Antibacterial Shabay 1L',
            category: 'Higiene Personal',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 28.0,
            total: 280.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104937',
            invoiceAmount: 1995.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple BNB',
            referenceNumber: 'QR-BNB-119203',
            amount: 1200.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104937',
            invoiceAmount: 1995.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008971',
            amount: 795.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Rosa Claros de Vaca',
          receiverDocument: 'CI 2819203 SC',
          receiverRelationship: 'Dueña',
          capturedAt: '13:14',
        },
      },
      {
        id: 'parada-111',
        sequence: 11,
        customerName: 'Supermercado IC Norte Sur',
        customerCode: 'CLI-8104',
        address: 'Av. Santos Dumont esq. 5to Anillo',
        zoneName: 'Zona Sur - Santos Dumont',
        saleChannel: 'Supermercado',
        deliveryNoteNumber: 'REM-2026-9051',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '9 min (1.8 km)',
        travelMinutes: 9,
        arrivedAt: '13:26',
        deliveredAt: '13:56',
        serviceDuration: '30 min',
        items: [
          {
            id: 'item-11',
            sku: 'VEN-LEV-SECA-500',
            productName: 'Levadura Seca Instantánea FACRULESA 500g Caja x20',
            category: 'Panificación',
            plannedQty: 10,
            deliveredQty: 10,
            returnedQty: 0,
            unitPrice: 380.0,
            total: 3800.0,
          },
          {
            id: 'item-11b',
            sku: 'VEN-CREM-WHIP-1L',
            productName: "Crema Chantilly Whip Topping Base Rich's 1L Caja x12",
            category: 'Pastelería',
            plannedQty: 5,
            deliveredQty: 5,
            returnedQty: 0,
            unitPrice: 350.0,
            total: 1750.0,
          },
          {
            id: 'item-11c',
            sku: 'VEN-FLEI-HORN-1K',
            productName: 'Polvo para Hornear Fleischmann 1kg Caja x10',
            category: 'Panificación',
            plannedQty: 20,
            deliveredQty: 20,
            returnedQty: 0,
            unitPrice: 45.0,
            total: 900.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104938',
            invoiceAmount: 6450.0,
            paymentMethod: 'TRANSFER',
            paymentMethodLabel: 'Transferencia Banco Ganadero',
            referenceNumber: 'TRF-BGA-991024',
            amount: 4450.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
          {
            invoiceId: 'FAC-104938',
            invoiceAmount: 6450.0,
            paymentMethod: 'CHECK',
            paymentMethodLabel: 'Cheque Banco Mercantil',
            referenceNumber: 'CHQ-BMSC-33019',
            amount: 2000.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Ing. Fabio Mendoza',
          receiverDocument: 'CI 4901928 SC',
          receiverRelationship: 'Jefe de Plataforma',
          capturedAt: '13:52',
        },
      },
      {
        id: 'parada-112',
        sequence: 12,
        customerName: 'Comercial El Pahuichi',
        customerCode: 'CLI-6019',
        address: 'Av. Radial 13 esq. Calle 5',
        zoneName: 'Zona Sur - Radial 13',
        saleChannel: 'Tradicional',
        deliveryNoteNumber: 'REM-2026-9052',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '10 min (2.2 km)',
        travelMinutes: 10,
        arrivedAt: '14:07',
        deliveredAt: '14:27',
        serviceDuration: '20 min',
        items: [
          {
            id: 'item-12',
            sku: 'VEN-MOCO-2L',
            productName: 'Refresco Mocochinchi VEMASSA 2L Pack x6',
            category: 'Bebidas Típicas',
            plannedQty: 20,
            deliveredQty: 20,
            returnedQty: 0,
            unitPrice: 48.0,
            total: 960.0,
          },
          {
            id: 'item-12b',
            sku: 'VEN-AGUA-SPER-2L',
            productName: 'Agua Purificada Speranza 2L Pack x6',
            category: 'Aguas',
            plannedQty: 15,
            deliveredQty: 15,
            returnedQty: 0,
            unitPrice: 32.0,
            total: 480.0,
          },
          {
            id: 'item-12c',
            sku: 'VEN-CALD-CAR-24',
            productName: 'Caldo Concentrado de Carne Kris x24 Cubos',
            category: 'Caldos y Sopas',
            plannedQty: 4,
            deliveredQty: 4,
            returnedQty: 0,
            unitPrice: 30.0,
            total: 120.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104939',
            invoiceAmount: 1560.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BMSC-110294',
            amount: 1560.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Guillermo Paz',
          receiverDocument: 'CI 3901823 SC',
          receiverRelationship: 'Propietario',
          capturedAt: '14:25',
        },
      },
    ],
  },
  {
    id: 'ot-100452',
    code: 100452,
    codeFormatted: 'OT-100452',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-20T07:00:00',
    completedDate: '2026-08-20T15:10:00',
    dateFormatted: '20/08/2026',
    dateIso: '2026-08-20',
    totalKm: 54.2,
    assignedWeightKg: 4210.0,
    assignedVolumeM3: 16.8,
    status: 'DISCREPANCY',
    statusLabel: 'Con discrepancia',
    truck: {
      id: 15,
      plate: '2489-XYZ',
      code: 'CAM-015',
      truckType: 'Furgón 6 Tn',
      isRefrigerated: false,
      capacityKg: 6000,
      capacityM3: 20.0,
    },
    driver: {
      name: 'Juan Pérez Montaño',
      phone: '+591 78901234',
      document: '4829103 SC',
    },
    helper: {
      name: 'Jorge Salces Pinto',
      phone: '+591 73491823',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 5,
      completedStops: 4,
      successRate: 80,
      totalInvoiced: 21300.0,
      totalCollected: 18100.0,
      collectedCash: 11500.0,
      collectedQr: 6600.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 490,
      driveDurationMinutes: 230,
      serviceDurationMinutes: 260,
    },
    logisticAssets: [
      {
        assetCode: 'PALLET-STD',
        assetName: 'Pallet Madera Estándar (1.20x1.00m)',
        dispatchedQty: 7,
        returnedQty: 6,
        varianceQty: -1,
        status: 'DISCREPANCY',
        notes: '1 pallet retenido en custodia en Mayorista La Casona (Vale #4401)',
      },
    ],
    paradas: [
      {
        id: 'parada-201',
        sequence: 1,
        customerName: 'Mayorista La Casona',
        customerCode: 'CLI-7120',
        address: 'Av. Brasil esq. 3er Anillo Externo',
        zoneName: 'Zona Este - Brasil',
        saleChannel: 'Mayorista',
        deliveryNoteNumber: 'REM-2026-9051',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '24 min (5.8 km)',
        travelMinutes: 24,
        arrivedAt: '07:45',
        deliveredAt: '08:40',
        serviceDuration: '55 min',
        items: [
          {
            id: 'item-201',
            sku: 'VEN-MAY-GALON',
            productName: 'Mayonesa Kris Galón 3.8L Caja x4',
            category: 'Salsas',
            plannedQty: 60,
            deliveredQty: 60,
            returnedQty: 0,
            unitPrice: 118.0,
            total: 7080.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104940',
            invoiceAmount: 7080.0,
            paymentMethod: 'CASH',
            paymentMethodLabel: 'Efectivo Contado',
            referenceNumber: 'REC-008920',
            amount: 7080.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Don Mario Justiniano',
          receiverDocument: 'CI 3109281 SC',
          receiverRelationship: 'Propietario',
          capturedAt: '08:35',
        },
      },
    ],
  },
  {
    id: 'ot-100453',
    code: 100453,
    codeFormatted: 'OT-100453',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-19T06:45:00',
    completedDate: '2026-08-19T13:30:00',
    dateFormatted: '19/08/2026',
    dateIso: '2026-08-19',
    totalKm: 38.0,
    assignedWeightKg: 2950.0,
    assignedVolumeM3: 11.2,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 18,
      plate: '1844-KLP',
      code: 'CAM-018',
      truckType: 'Furgón 4 Tn',
      isRefrigerated: false,
      capacityKg: 4000,
      capacityM3: 14.0,
    },
    driver: {
      name: 'Miguel Torrico Zeballos',
      phone: '+591 77334455',
      document: '6901923 SC',
    },
    helper: {
      name: 'David Flores Rojas',
      phone: '+591 78912304',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 4,
      completedStops: 4,
      successRate: 100,
      totalInvoiced: 16800.0,
      totalCollected: 16800.0,
      collectedCash: 8400.0,
      collectedQr: 8400.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 405,
      driveDurationMinutes: 160,
      serviceDurationMinutes: 245,
    },
    logisticAssets: [
      {
        assetCode: 'PALLET-STD',
        assetName: 'Pallet Madera Estándar (1.20x1.00m)',
        dispatchedQty: 4,
        returnedQty: 4,
        varianceQty: 0,
        status: 'RETURNED_OK',
      },
    ],
    paradas: [
      {
        id: 'parada-301',
        sequence: 1,
        customerName: 'Supermercados Tía Santos Dumont',
        customerCode: 'CLI-8098',
        address: 'Av. Santos Dumont esq. 4to Anillo',
        zoneName: 'Zona Sur - Santos Dumont',
        saleChannel: 'Supermercado',
        deliveryNoteNumber: 'REM-2026-8910',
        status: 'DELIVERED',
        resultCode: 'EXITOSO',
        travelTimeFromPrevious: '22 min (5.0 km)',
        travelMinutes: 22,
        arrivedAt: '07:20',
        deliveredAt: '08:10',
        serviceDuration: '50 min',
        items: [
          {
            id: 'item-301',
            sku: 'VEN-FRUS-DUR-2L',
            productName: 'Jugo Frussion Durazno con Pulpa 2L Pack x6',
            category: 'Bebidas Líquidas',
            plannedQty: 30,
            deliveredQty: 30,
            returnedQty: 0,
            unitPrice: 120.0,
            total: 3600.0,
          },
        ],
        payments: [
          {
            invoiceId: 'FAC-104880',
            invoiceAmount: 3600.0,
            paymentMethod: 'QR',
            paymentMethodLabel: 'Pago QR Simple',
            referenceNumber: 'QR-BMSC-330192',
            amount: 3600.0,
            currency: 'BOB',
            status: 'COMPLETED',
          },
        ],
        proofOfDelivery: {
          receiverName: 'Hernán Saucedo',
          receiverDocument: 'CI 4019283 SC',
          receiverRelationship: 'Jefe de Tienda',
          capturedAt: '08:05',
        },
      },
    ],
  },
  {
    id: 'ot-100454',
    code: 100454,
    codeFormatted: 'OT-100454',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-18T06:30:00',
    completedDate: '2026-08-18T16:00:00',
    dateFormatted: '18/08/2026',
    dateIso: '2026-08-18',
    totalKm: 62.1,
    assignedWeightKg: 5200.0,
    assignedVolumeM3: 19.5,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 20,
      plate: '4120-NMK',
      code: 'CAM-020',
      truckType: 'Furgón 7 Tn',
      isRefrigerated: true,
      capacityKg: 7000,
      capacityM3: 22.0,
    },
    driver: {
      name: 'Fernando Áñez Hurtado',
      phone: '+591 76019283',
      document: '3819023 SC',
    },
    helper: {
      name: 'Sergio Morales Claros',
      phone: '+591 77481920',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 5,
      completedStops: 5,
      successRate: 100,
      totalInvoiced: 34900.0,
      totalCollected: 34900.0,
      collectedCash: 16500.0,
      collectedQr: 10400.0,
      collectedTransfer: 8000.0,
      totalDurationMinutes: 570,
      driveDurationMinutes: 260,
      serviceDurationMinutes: 310,
    },
    logisticAssets: [
      {
        assetCode: 'PALLET-STD',
        assetName: 'Pallet Madera Estándar (1.20x1.00m)',
        dispatchedQty: 8,
        returnedQty: 8,
        varianceQty: 0,
        status: 'RETURNED_OK',
      },
    ],
    paradas: [],
  },
  {
    id: 'ot-100455',
    code: 100455,
    codeFormatted: 'OT-100455',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-17T07:15:00',
    completedDate: '2026-08-17T14:20:00',
    dateFormatted: '17/08/2026',
    dateIso: '2026-08-17',
    totalKm: 41.5,
    assignedWeightKg: 3100.0,
    assignedVolumeM3: 12.0,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 22,
      plate: '5021-PQR',
      code: 'CAM-022',
      truckType: 'Furgón 4.5 Tn',
      isRefrigerated: false,
      capacityKg: 4500,
      capacityM3: 15.0,
    },
    driver: {
      name: 'Pedro Morales Cuéllar',
      phone: '+591 71092834',
      document: '4910294 SC',
    },
    helper: {
      name: 'Esteban Paz Rivero',
      phone: '+591 78192039',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 4,
      completedStops: 4,
      successRate: 100,
      totalInvoiced: 19400.0,
      totalCollected: 19400.0,
      collectedCash: 12400.0,
      collectedQr: 7000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 425,
      driveDurationMinutes: 180,
      serviceDurationMinutes: 245,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100450',
    code: 100450,
    codeFormatted: 'OT-100450',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-16T06:30:00',
    completedDate: '2026-08-16T13:45:00',
    dateFormatted: '16/08/2026',
    dateIso: '2026-08-16',
    totalKm: 35.8,
    assignedWeightKg: 2800.0,
    assignedVolumeM3: 10.5,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 12,
      plate: '3012-ABC',
      code: 'CAM-012',
      truckType: 'Furgón 5 Tn',
      isRefrigerated: true,
      capacityKg: 5000,
      capacityM3: 18.0,
    },
    driver: {
      name: 'Carlos Mendoza Vargas',
      phone: '+591 76543210',
      document: '5498214 SC',
    },
    helper: {
      name: 'Roberto Quispe Lima',
      phone: '+591 71239845',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 5,
      completedStops: 5,
      successRate: 100,
      totalInvoiced: 22100.0,
      totalCollected: 22100.0,
      collectedCash: 11000.0,
      collectedQr: 8100.0,
      collectedTransfer: 3000.0,
      totalDurationMinutes: 435,
      driveDurationMinutes: 190,
      serviceDurationMinutes: 245,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100449',
    code: 100449,
    codeFormatted: 'OT-100449',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-15T07:00:00',
    completedDate: '2026-08-15T15:30:00',
    dateFormatted: '15/08/2026',
    dateIso: '2026-08-15',
    totalKm: 51.4,
    assignedWeightKg: 4600.0,
    assignedVolumeM3: 17.2,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 15,
      plate: '2489-XYZ',
      code: 'CAM-015',
      truckType: 'Furgón 6 Tn',
      isRefrigerated: false,
      capacityKg: 6000,
      capacityM3: 20.0,
    },
    driver: {
      name: 'Juan Pérez Montaño',
      phone: '+591 78901234',
      document: '4829103 SC',
    },
    helper: {
      name: 'Jorge Salces Pinto',
      phone: '+591 73491823',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 6,
      completedStops: 6,
      successRate: 100,
      totalInvoiced: 31200.0,
      totalCollected: 31200.0,
      collectedCash: 18000.0,
      collectedQr: 13200.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 510,
      driveDurationMinutes: 220,
      serviceDurationMinutes: 290,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100448',
    code: 100448,
    codeFormatted: 'OT-100448',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-14T06:45:00',
    completedDate: '2026-08-14T14:15:00',
    dateFormatted: '14/08/2026',
    dateIso: '2026-08-14',
    totalKm: 44.0,
    assignedWeightKg: 3500.0,
    assignedVolumeM3: 13.8,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 18,
      plate: '1844-KLP',
      code: 'CAM-018',
      truckType: 'Furgón 4 Tn',
      isRefrigerated: false,
      capacityKg: 4000,
      capacityM3: 14.0,
    },
    driver: {
      name: 'Miguel Torrico Zeballos',
      phone: '+591 77334455',
      document: '6901923 SC',
    },
    helper: {
      name: 'David Flores Rojas',
      phone: '+591 78912304',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 5,
      completedStops: 5,
      successRate: 100,
      totalInvoiced: 24500.0,
      totalCollected: 24500.0,
      collectedCash: 14000.0,
      collectedQr: 10500.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 450,
      driveDurationMinutes: 195,
      serviceDurationMinutes: 255,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100447',
    code: 100447,
    codeFormatted: 'OT-100447',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-13T07:15:00',
    completedDate: '2026-08-13T16:00:00',
    dateFormatted: '13/08/2026',
    dateIso: '2026-08-13',
    totalKm: 58.2,
    assignedWeightKg: 4900.0,
    assignedVolumeM3: 18.4,
    status: 'DISCREPANCY',
    statusLabel: 'Con discrepancia',
    truck: {
      id: 20,
      plate: '4120-NMK',
      code: 'CAM-020',
      truckType: 'Furgón 7 Tn',
      isRefrigerated: true,
      capacityKg: 7000,
      capacityM3: 22.0,
    },
    driver: {
      name: 'Fernando Áñez Hurtado',
      phone: '+591 76019283',
      document: '3819023 SC',
    },
    helper: {
      name: 'Sergio Morales Claros',
      phone: '+591 77481920',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 6,
      completedStops: 5,
      successRate: 83.3,
      totalInvoiced: 29800.0,
      totalCollected: 26100.0,
      collectedCash: 15000.0,
      collectedQr: 11100.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 525,
      driveDurationMinutes: 240,
      serviceDurationMinutes: 285,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100446',
    code: 100446,
    codeFormatted: 'OT-100446',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-12T06:30:00',
    completedDate: '2026-08-12T13:50:00',
    dateFormatted: '12/08/2026',
    dateIso: '2026-08-12',
    totalKm: 39.4,
    assignedWeightKg: 3200.0,
    assignedVolumeM3: 12.6,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 22,
      plate: '5021-PQR',
      code: 'CAM-022',
      truckType: 'Furgón 4.5 Tn',
      isRefrigerated: false,
      capacityKg: 4500,
      capacityM3: 15.0,
    },
    driver: {
      name: 'Pedro Morales Cuéllar',
      phone: '+591 71092834',
      document: '4910294 SC',
    },
    helper: {
      name: 'Esteban Paz Rivero',
      phone: '+591 78192039',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 4,
      completedStops: 4,
      successRate: 100,
      totalInvoiced: 20100.0,
      totalCollected: 20100.0,
      collectedCash: 12100.0,
      collectedQr: 8000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 440,
      driveDurationMinutes: 185,
      serviceDurationMinutes: 255,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100445',
    code: 100445,
    codeFormatted: 'OT-100445',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-11T06:45:00',
    completedDate: '2026-08-11T14:30:00',
    dateFormatted: '11/08/2026',
    dateIso: '2026-08-11',
    totalKm: 42.1,
    assignedWeightKg: 3600.0,
    assignedVolumeM3: 14.1,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 12,
      plate: '3012-ABC',
      code: 'CAM-012',
      truckType: 'Furgón 5 Tn',
      isRefrigerated: true,
      capacityKg: 5000,
      capacityM3: 18.0,
    },
    driver: {
      name: 'Carlos Mendoza Vargas',
      phone: '+591 76543210',
      document: '5498214 SC',
    },
    helper: {
      name: 'Roberto Quispe Lima',
      phone: '+591 71239845',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 5,
      completedStops: 5,
      successRate: 100,
      totalInvoiced: 25400.0,
      totalCollected: 25400.0,
      collectedCash: 15400.0,
      collectedQr: 10000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 465,
      driveDurationMinutes: 195,
      serviceDurationMinutes: 270,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100444',
    code: 100444,
    codeFormatted: 'OT-100444',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-10T07:00:00',
    completedDate: '2026-08-10T15:45:00',
    dateFormatted: '10/08/2026',
    dateIso: '2026-08-10',
    totalKm: 55.0,
    assignedWeightKg: 4400.0,
    assignedVolumeM3: 16.9,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 15,
      plate: '2489-XYZ',
      code: 'CAM-015',
      truckType: 'Furgón 6 Tn',
      isRefrigerated: false,
      capacityKg: 6000,
      capacityM3: 20.0,
    },
    driver: {
      name: 'Juan Pérez Montaño',
      phone: '+591 78901234',
      document: '4829103 SC',
    },
    helper: {
      name: 'Jorge Salces Pinto',
      phone: '+591 73491823',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 6,
      completedStops: 6,
      successRate: 100,
      totalInvoiced: 30500.0,
      totalCollected: 30500.0,
      collectedCash: 17500.0,
      collectedQr: 13000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 525,
      driveDurationMinutes: 235,
      serviceDurationMinutes: 290,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100443',
    code: 100443,
    codeFormatted: 'OT-100443',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-08T06:30:00',
    completedDate: '2026-08-08T13:40:00',
    dateFormatted: '08/08/2026',
    dateIso: '2026-08-08',
    totalKm: 36.2,
    assignedWeightKg: 2700.0,
    assignedVolumeM3: 10.2,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 18,
      plate: '1844-KLP',
      code: 'CAM-018',
      truckType: 'Furgón 4 Tn',
      isRefrigerated: false,
      capacityKg: 4000,
      capacityM3: 14.0,
    },
    driver: {
      name: 'Miguel Torrico Zeballos',
      phone: '+591 77334455',
      document: '6901923 SC',
    },
    helper: {
      name: 'David Flores Rojas',
      phone: '+591 78912304',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 4,
      completedStops: 4,
      successRate: 100,
      totalInvoiced: 17900.0,
      totalCollected: 17900.0,
      collectedCash: 10900.0,
      collectedQr: 7000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 430,
      driveDurationMinutes: 180,
      serviceDurationMinutes: 250,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100442',
    code: 100442,
    codeFormatted: 'OT-100442',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-07T07:15:00',
    completedDate: '2026-08-07T16:10:00',
    dateFormatted: '07/08/2026',
    dateIso: '2026-08-07',
    totalKm: 60.5,
    assignedWeightKg: 5100.0,
    assignedVolumeM3: 19.1,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 20,
      plate: '4120-NMK',
      code: 'CAM-020',
      truckType: 'Furgón 7 Tn',
      isRefrigerated: true,
      capacityKg: 7000,
      capacityM3: 22.0,
    },
    driver: {
      name: 'Fernando Áñez Hurtado',
      phone: '+591 76019283',
      document: '3819023 SC',
    },
    helper: {
      name: 'Sergio Morales Claros',
      phone: '+591 77481920',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 6,
      completedStops: 6,
      successRate: 100,
      totalInvoiced: 33800.0,
      totalCollected: 33800.0,
      collectedCash: 19800.0,
      collectedQr: 14000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 535,
      driveDurationMinutes: 250,
      serviceDurationMinutes: 285,
    },
    logisticAssets: [],
    paradas: [],
  },
  {
    id: 'ot-100441',
    code: 100441,
    codeFormatted: 'OT-100441',
    distributorName: 'Distribuidora Central Santa Cruz',
    departureDate: '2026-08-05T06:30:00',
    completedDate: '2026-08-05T14:10:00',
    dateFormatted: '05/08/2026',
    dateIso: '2026-08-05',
    totalKm: 40.0,
    assignedWeightKg: 3050.0,
    assignedVolumeM3: 11.8,
    status: 'COMPLETED',
    statusLabel: 'Completado',
    truck: {
      id: 22,
      plate: '5021-PQR',
      code: 'CAM-022',
      truckType: 'Furgón 4.5 Tn',
      isRefrigerated: false,
      capacityKg: 4500,
      capacityM3: 15.0,
    },
    driver: {
      name: 'Pedro Morales Cuéllar',
      phone: '+591 71092834',
      document: '4910294 SC',
    },
    helper: {
      name: 'Esteban Paz Rivero',
      phone: '+591 78192039',
    },
    supervisor: {
      name: 'Ing. Marco Antonio Vaca',
    },
    kpis: {
      totalStops: 4,
      completedStops: 4,
      successRate: 100,
      totalInvoiced: 18500.0,
      totalCollected: 18500.0,
      collectedCash: 11500.0,
      collectedQr: 7000.0,
      collectedTransfer: 0.0,
      totalDurationMinutes: 460,
      driveDurationMinutes: 190,
      serviceDurationMinutes: 270,
    },
    logisticAssets: [],
    paradas: [],
  },
]
